// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: internal/api/grpc/proto/protofile.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SponsorService_Sponsor_FullMethodName                  = "/proto.SponsorService/Sponsor"
	SponsorService_GetRestaurantSponsorship_FullMethodName = "/proto.SponsorService/GetRestaurantSponsorship"
)

// SponsorServiceClient is the client API for SponsorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SponsorServiceClient interface {
	Sponsor(ctx context.Context, in *SponsorshipRequest, opts ...grpc.CallOption) (*SponsorshipResponse, error)
	GetRestaurantSponsorship(ctx context.Context, in *GetRestaurantSponsorshipRequest, opts ...grpc.CallOption) (*SponsorshipResponse, error)
}

type sponsorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSponsorServiceClient(cc grpc.ClientConnInterface) SponsorServiceClient {
	return &sponsorServiceClient{cc}
}

func (c *sponsorServiceClient) Sponsor(ctx context.Context, in *SponsorshipRequest, opts ...grpc.CallOption) (*SponsorshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SponsorshipResponse)
	err := c.cc.Invoke(ctx, SponsorService_Sponsor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sponsorServiceClient) GetRestaurantSponsorship(ctx context.Context, in *GetRestaurantSponsorshipRequest, opts ...grpc.CallOption) (*SponsorshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SponsorshipResponse)
	err := c.cc.Invoke(ctx, SponsorService_GetRestaurantSponsorship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SponsorServiceServer is the server API for SponsorService service.
// All implementations must embed UnimplementedSponsorServiceServer
// for forward compatibility.
type SponsorServiceServer interface {
	Sponsor(context.Context, *SponsorshipRequest) (*SponsorshipResponse, error)
	GetRestaurantSponsorship(context.Context, *GetRestaurantSponsorshipRequest) (*SponsorshipResponse, error)
	mustEmbedUnimplementedSponsorServiceServer()
}

// UnimplementedSponsorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSponsorServiceServer struct{}

func (UnimplementedSponsorServiceServer) Sponsor(context.Context, *SponsorshipRequest) (*SponsorshipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sponsor not implemented")
}
func (UnimplementedSponsorServiceServer) GetRestaurantSponsorship(context.Context, *GetRestaurantSponsorshipRequest) (*SponsorshipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRestaurantSponsorship not implemented")
}
func (UnimplementedSponsorServiceServer) mustEmbedUnimplementedSponsorServiceServer() {}
func (UnimplementedSponsorServiceServer) testEmbeddedByValue()                        {}

// UnsafeSponsorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SponsorServiceServer will
// result in compilation errors.
type UnsafeSponsorServiceServer interface {
	mustEmbedUnimplementedSponsorServiceServer()
}

func RegisterSponsorServiceServer(s grpc.ServiceRegistrar, srv SponsorServiceServer) {
	// If the following call panics, it indicates UnimplementedSponsorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SponsorService_ServiceDesc, srv)
}

func _SponsorService_Sponsor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SponsorshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SponsorServiceServer).Sponsor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SponsorService_Sponsor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SponsorServiceServer).Sponsor(ctx, req.(*SponsorshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SponsorService_GetRestaurantSponsorship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestaurantSponsorshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SponsorServiceServer).GetRestaurantSponsorship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SponsorService_GetRestaurantSponsorship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SponsorServiceServer).GetRestaurantSponsorship(ctx, req.(*GetRestaurantSponsorshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SponsorService_ServiceDesc is the grpc.ServiceDesc for SponsorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SponsorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SponsorService",
	HandlerType: (*SponsorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sponsor",
			Handler:    _SponsorService_Sponsor_Handler,
		},
		{
			MethodName: "GetRestaurantSponsorship",
			Handler:    _SponsorService_GetRestaurantSponsorship_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/grpc/proto/protofile.proto",
}

const (
	RestaurantToSponsorService_GetRestaurantSponsorship_FullMethodName = "/proto.RestaurantToSponsorService/GetRestaurantSponsorship"
)

// RestaurantToSponsorServiceClient is the client API for RestaurantToSponsorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestaurantToSponsorServiceClient interface {
	GetRestaurantSponsorship(ctx context.Context, in *GetRestaurantSponsorshipRequest, opts ...grpc.CallOption) (*GetRestaurantSponsorshipResponse, error)
}

type restaurantToSponsorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRestaurantToSponsorServiceClient(cc grpc.ClientConnInterface) RestaurantToSponsorServiceClient {
	return &restaurantToSponsorServiceClient{cc}
}

func (c *restaurantToSponsorServiceClient) GetRestaurantSponsorship(ctx context.Context, in *GetRestaurantSponsorshipRequest, opts ...grpc.CallOption) (*GetRestaurantSponsorshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRestaurantSponsorshipResponse)
	err := c.cc.Invoke(ctx, RestaurantToSponsorService_GetRestaurantSponsorship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestaurantToSponsorServiceServer is the server API for RestaurantToSponsorService service.
// All implementations must embed UnimplementedRestaurantToSponsorServiceServer
// for forward compatibility.
type RestaurantToSponsorServiceServer interface {
	GetRestaurantSponsorship(context.Context, *GetRestaurantSponsorshipRequest) (*GetRestaurantSponsorshipResponse, error)
	mustEmbedUnimplementedRestaurantToSponsorServiceServer()
}

// UnimplementedRestaurantToSponsorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRestaurantToSponsorServiceServer struct{}

func (UnimplementedRestaurantToSponsorServiceServer) GetRestaurantSponsorship(context.Context, *GetRestaurantSponsorshipRequest) (*GetRestaurantSponsorshipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRestaurantSponsorship not implemented")
}
func (UnimplementedRestaurantToSponsorServiceServer) mustEmbedUnimplementedRestaurantToSponsorServiceServer() {
}
func (UnimplementedRestaurantToSponsorServiceServer) testEmbeddedByValue() {}

// UnsafeRestaurantToSponsorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestaurantToSponsorServiceServer will
// result in compilation errors.
type UnsafeRestaurantToSponsorServiceServer interface {
	mustEmbedUnimplementedRestaurantToSponsorServiceServer()
}

func RegisterRestaurantToSponsorServiceServer(s grpc.ServiceRegistrar, srv RestaurantToSponsorServiceServer) {
	// If the following call panics, it indicates UnimplementedRestaurantToSponsorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RestaurantToSponsorService_ServiceDesc, srv)
}

func _RestaurantToSponsorService_GetRestaurantSponsorship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestaurantSponsorshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantToSponsorServiceServer).GetRestaurantSponsorship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantToSponsorService_GetRestaurantSponsorship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantToSponsorServiceServer).GetRestaurantSponsorship(ctx, req.(*GetRestaurantSponsorshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RestaurantToSponsorService_ServiceDesc is the grpc.ServiceDesc for RestaurantToSponsorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestaurantToSponsorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RestaurantToSponsorService",
	HandlerType: (*RestaurantToSponsorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRestaurantSponsorship",
			Handler:    _RestaurantToSponsorService_GetRestaurantSponsorship_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/grpc/proto/protofile.proto",
}

const (
	PaymentCommandService_MakePayment_FullMethodName = "/proto.PaymentCommandService/MakePayment"
)

// PaymentCommandServiceClient is the client API for PaymentCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentCommandServiceClient interface {
	MakePayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
}

type paymentCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentCommandServiceClient(cc grpc.ClientConnInterface) PaymentCommandServiceClient {
	return &paymentCommandServiceClient{cc}
}

func (c *paymentCommandServiceClient) MakePayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, PaymentCommandService_MakePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentCommandServiceServer is the server API for PaymentCommandService service.
// All implementations must embed UnimplementedPaymentCommandServiceServer
// for forward compatibility.
type PaymentCommandServiceServer interface {
	MakePayment(context.Context, *PaymentRequest) (*PaymentResponse, error)
	mustEmbedUnimplementedPaymentCommandServiceServer()
}

// UnimplementedPaymentCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentCommandServiceServer struct{}

func (UnimplementedPaymentCommandServiceServer) MakePayment(context.Context, *PaymentRequest) (*PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MakePayment not implemented")
}
func (UnimplementedPaymentCommandServiceServer) mustEmbedUnimplementedPaymentCommandServiceServer() {}
func (UnimplementedPaymentCommandServiceServer) testEmbeddedByValue()                               {}

// UnsafePaymentCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentCommandServiceServer will
// result in compilation errors.
type UnsafePaymentCommandServiceServer interface {
	mustEmbedUnimplementedPaymentCommandServiceServer()
}

func RegisterPaymentCommandServiceServer(s grpc.ServiceRegistrar, srv PaymentCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentCommandService_ServiceDesc, srv)
}

func _PaymentCommandService_MakePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentCommandServiceServer).MakePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentCommandService_MakePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentCommandServiceServer).MakePayment(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentCommandService_ServiceDesc is the grpc.ServiceDesc for PaymentCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PaymentCommandService",
	HandlerType: (*PaymentCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakePayment",
			Handler:    _PaymentCommandService_MakePayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/grpc/proto/protofile.proto",
}
