// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.6
// source: internal/api/grpc/proto/protofile.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	SponsorService_PingPong_FullMethodName                 = "/proto.SponsorService/PingPong"
	SponsorService_Sponsor_FullMethodName                  = "/proto.SponsorService/Sponsor"
	SponsorService_GetRestaurantSponsorship_FullMethodName = "/proto.SponsorService/GetRestaurantSponsorship"
)

// SponsorServiceClient is the client API for SponsorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SponsorServiceClient interface {
	PingPong(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
	Sponsor(ctx context.Context, in *SponsorshipRequest, opts ...grpc.CallOption) (*SponsorshipResponse, error)
	GetRestaurantSponsorship(ctx context.Context, in *GetRestaurantSponsorshipRequest, opts ...grpc.CallOption) (*SponsorshipResponse, error)
}

type sponsorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSponsorServiceClient(cc grpc.ClientConnInterface) SponsorServiceClient {
	return &sponsorServiceClient{cc}
}

func (c *sponsorServiceClient) PingPong(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pong)
	err := c.cc.Invoke(ctx, SponsorService_PingPong_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sponsorServiceClient) Sponsor(ctx context.Context, in *SponsorshipRequest, opts ...grpc.CallOption) (*SponsorshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SponsorshipResponse)
	err := c.cc.Invoke(ctx, SponsorService_Sponsor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sponsorServiceClient) GetRestaurantSponsorship(ctx context.Context, in *GetRestaurantSponsorshipRequest, opts ...grpc.CallOption) (*SponsorshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SponsorshipResponse)
	err := c.cc.Invoke(ctx, SponsorService_GetRestaurantSponsorship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SponsorServiceServer is the server API for SponsorService service.
// All implementations must embed UnimplementedSponsorServiceServer
// for forward compatibility
type SponsorServiceServer interface {
	PingPong(context.Context, *Ping) (*Pong, error)
	Sponsor(context.Context, *SponsorshipRequest) (*SponsorshipResponse, error)
	GetRestaurantSponsorship(context.Context, *GetRestaurantSponsorshipRequest) (*SponsorshipResponse, error)
	mustEmbedUnimplementedSponsorServiceServer()
}

// UnimplementedSponsorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSponsorServiceServer struct {
}

func (UnimplementedSponsorServiceServer) PingPong(context.Context, *Ping) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingPong not implemented")
}
func (UnimplementedSponsorServiceServer) Sponsor(context.Context, *SponsorshipRequest) (*SponsorshipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sponsor not implemented")
}
func (UnimplementedSponsorServiceServer) GetRestaurantSponsorship(context.Context, *GetRestaurantSponsorshipRequest) (*SponsorshipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRestaurantSponsorship not implemented")
}
func (UnimplementedSponsorServiceServer) mustEmbedUnimplementedSponsorServiceServer() {}

// UnsafeSponsorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SponsorServiceServer will
// result in compilation errors.
type UnsafeSponsorServiceServer interface {
	mustEmbedUnimplementedSponsorServiceServer()
}

func RegisterSponsorServiceServer(s grpc.ServiceRegistrar, srv SponsorServiceServer) {
	s.RegisterService(&SponsorService_ServiceDesc, srv)
}

func _SponsorService_PingPong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SponsorServiceServer).PingPong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SponsorService_PingPong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SponsorServiceServer).PingPong(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

func _SponsorService_Sponsor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SponsorshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SponsorServiceServer).Sponsor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SponsorService_Sponsor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SponsorServiceServer).Sponsor(ctx, req.(*SponsorshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SponsorService_GetRestaurantSponsorship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestaurantSponsorshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SponsorServiceServer).GetRestaurantSponsorship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SponsorService_GetRestaurantSponsorship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SponsorServiceServer).GetRestaurantSponsorship(ctx, req.(*GetRestaurantSponsorshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SponsorService_ServiceDesc is the grpc.ServiceDesc for SponsorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SponsorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SponsorService",
	HandlerType: (*SponsorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingPong",
			Handler:    _SponsorService_PingPong_Handler,
		},
		{
			MethodName: "Sponsor",
			Handler:    _SponsorService_Sponsor_Handler,
		},
		{
			MethodName: "GetRestaurantSponsorship",
			Handler:    _SponsorService_GetRestaurantSponsorship_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/grpc/proto/protofile.proto",
}

const (
	RestaurantService_GetRestaurantDetails_FullMethodName = "/proto.RestaurantService/GetRestaurantDetails"
)

// RestaurantServiceClient is the client API for RestaurantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestaurantServiceClient interface {
	GetRestaurantDetails(ctx context.Context, in *GetRestaurantDetailsRequest, opts ...grpc.CallOption) (*GetRestaurantDetailsResponse, error)
}

type restaurantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRestaurantServiceClient(cc grpc.ClientConnInterface) RestaurantServiceClient {
	return &restaurantServiceClient{cc}
}

func (c *restaurantServiceClient) GetRestaurantDetails(ctx context.Context, in *GetRestaurantDetailsRequest, opts ...grpc.CallOption) (*GetRestaurantDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRestaurantDetailsResponse)
	err := c.cc.Invoke(ctx, RestaurantService_GetRestaurantDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestaurantServiceServer is the server API for RestaurantService service.
// All implementations must embed UnimplementedRestaurantServiceServer
// for forward compatibility
type RestaurantServiceServer interface {
	GetRestaurantDetails(context.Context, *GetRestaurantDetailsRequest) (*GetRestaurantDetailsResponse, error)
	mustEmbedUnimplementedRestaurantServiceServer()
}

// UnimplementedRestaurantServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRestaurantServiceServer struct {
}

func (UnimplementedRestaurantServiceServer) GetRestaurantDetails(context.Context, *GetRestaurantDetailsRequest) (*GetRestaurantDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRestaurantDetails not implemented")
}
func (UnimplementedRestaurantServiceServer) mustEmbedUnimplementedRestaurantServiceServer() {}

// UnsafeRestaurantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestaurantServiceServer will
// result in compilation errors.
type UnsafeRestaurantServiceServer interface {
	mustEmbedUnimplementedRestaurantServiceServer()
}

func RegisterRestaurantServiceServer(s grpc.ServiceRegistrar, srv RestaurantServiceServer) {
	s.RegisterService(&RestaurantService_ServiceDesc, srv)
}

func _RestaurantService_GetRestaurantDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestaurantDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).GetRestaurantDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_GetRestaurantDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).GetRestaurantDetails(ctx, req.(*GetRestaurantDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RestaurantService_ServiceDesc is the grpc.ServiceDesc for RestaurantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestaurantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RestaurantService",
	HandlerType: (*RestaurantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRestaurantDetails",
			Handler:    _RestaurantService_GetRestaurantDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/grpc/proto/protofile.proto",
}
