// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.6
// source: internal/api/grpc/proto/protofile.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	TemplateService_PingPong_FullMethodName            = "/proto.TemplateService/PingPong"
	TemplateService_ManyPings_FullMethodName           = "/proto.TemplateService/ManyPings"
	TemplateService_ManyPongs_FullMethodName           = "/proto.TemplateService/ManyPongs"
	TemplateService_ManyPingPongs_FullMethodName       = "/proto.TemplateService/ManyPingPongs"
	TemplateService_GetPaginatedExample_FullMethodName = "/proto.TemplateService/GetPaginatedExample"
)

// TemplateServiceClient is the client API for TemplateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemplateServiceClient interface {
	PingPong(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
	ManyPings(ctx context.Context, opts ...grpc.CallOption) (TemplateService_ManyPingsClient, error)
	ManyPongs(ctx context.Context, in *Ping, opts ...grpc.CallOption) (TemplateService_ManyPongsClient, error)
	ManyPingPongs(ctx context.Context, opts ...grpc.CallOption) (TemplateService_ManyPingPongsClient, error)
	GetPaginatedExample(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*PaginationResponse, error)
}

type templateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplateServiceClient(cc grpc.ClientConnInterface) TemplateServiceClient {
	return &templateServiceClient{cc}
}

func (c *templateServiceClient) PingPong(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pong)
	err := c.cc.Invoke(ctx, TemplateService_PingPong_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateServiceClient) ManyPings(ctx context.Context, opts ...grpc.CallOption) (TemplateService_ManyPingsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TemplateService_ServiceDesc.Streams[0], TemplateService_ManyPings_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &templateServiceManyPingsClient{ClientStream: stream}
	return x, nil
}

type TemplateService_ManyPingsClient interface {
	Send(*Ping) error
	CloseAndRecv() (*Pong, error)
	grpc.ClientStream
}

type templateServiceManyPingsClient struct {
	grpc.ClientStream
}

func (x *templateServiceManyPingsClient) Send(m *Ping) error {
	return x.ClientStream.SendMsg(m)
}

func (x *templateServiceManyPingsClient) CloseAndRecv() (*Pong, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Pong)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *templateServiceClient) ManyPongs(ctx context.Context, in *Ping, opts ...grpc.CallOption) (TemplateService_ManyPongsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TemplateService_ServiceDesc.Streams[1], TemplateService_ManyPongs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &templateServiceManyPongsClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TemplateService_ManyPongsClient interface {
	Recv() (*Pong, error)
	grpc.ClientStream
}

type templateServiceManyPongsClient struct {
	grpc.ClientStream
}

func (x *templateServiceManyPongsClient) Recv() (*Pong, error) {
	m := new(Pong)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *templateServiceClient) ManyPingPongs(ctx context.Context, opts ...grpc.CallOption) (TemplateService_ManyPingPongsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TemplateService_ServiceDesc.Streams[2], TemplateService_ManyPingPongs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &templateServiceManyPingPongsClient{ClientStream: stream}
	return x, nil
}

type TemplateService_ManyPingPongsClient interface {
	Send(*Ping) error
	Recv() (*Pong, error)
	grpc.ClientStream
}

type templateServiceManyPingPongsClient struct {
	grpc.ClientStream
}

func (x *templateServiceManyPingPongsClient) Send(m *Ping) error {
	return x.ClientStream.SendMsg(m)
}

func (x *templateServiceManyPingPongsClient) Recv() (*Pong, error) {
	m := new(Pong)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *templateServiceClient) GetPaginatedExample(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*PaginationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaginationResponse)
	err := c.cc.Invoke(ctx, TemplateService_GetPaginatedExample_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplateServiceServer is the server API for TemplateService service.
// All implementations must embed UnimplementedTemplateServiceServer
// for forward compatibility
type TemplateServiceServer interface {
	PingPong(context.Context, *Ping) (*Pong, error)
	ManyPings(TemplateService_ManyPingsServer) error
	ManyPongs(*Ping, TemplateService_ManyPongsServer) error
	ManyPingPongs(TemplateService_ManyPingPongsServer) error
	GetPaginatedExample(context.Context, *PaginationRequest) (*PaginationResponse, error)
	mustEmbedUnimplementedTemplateServiceServer()
}

// UnimplementedTemplateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTemplateServiceServer struct {
}

func (UnimplementedTemplateServiceServer) PingPong(context.Context, *Ping) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingPong not implemented")
}
func (UnimplementedTemplateServiceServer) ManyPings(TemplateService_ManyPingsServer) error {
	return status.Errorf(codes.Unimplemented, "method ManyPings not implemented")
}
func (UnimplementedTemplateServiceServer) ManyPongs(*Ping, TemplateService_ManyPongsServer) error {
	return status.Errorf(codes.Unimplemented, "method ManyPongs not implemented")
}
func (UnimplementedTemplateServiceServer) ManyPingPongs(TemplateService_ManyPingPongsServer) error {
	return status.Errorf(codes.Unimplemented, "method ManyPingPongs not implemented")
}
func (UnimplementedTemplateServiceServer) GetPaginatedExample(context.Context, *PaginationRequest) (*PaginationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaginatedExample not implemented")
}
func (UnimplementedTemplateServiceServer) mustEmbedUnimplementedTemplateServiceServer() {}

// UnsafeTemplateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemplateServiceServer will
// result in compilation errors.
type UnsafeTemplateServiceServer interface {
	mustEmbedUnimplementedTemplateServiceServer()
}

func RegisterTemplateServiceServer(s grpc.ServiceRegistrar, srv TemplateServiceServer) {
	s.RegisterService(&TemplateService_ServiceDesc, srv)
}

func _TemplateService_PingPong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServiceServer).PingPong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateService_PingPong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServiceServer).PingPong(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateService_ManyPings_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TemplateServiceServer).ManyPings(&templateServiceManyPingsServer{ServerStream: stream})
}

type TemplateService_ManyPingsServer interface {
	SendAndClose(*Pong) error
	Recv() (*Ping, error)
	grpc.ServerStream
}

type templateServiceManyPingsServer struct {
	grpc.ServerStream
}

func (x *templateServiceManyPingsServer) SendAndClose(m *Pong) error {
	return x.ServerStream.SendMsg(m)
}

func (x *templateServiceManyPingsServer) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TemplateService_ManyPongs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Ping)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TemplateServiceServer).ManyPongs(m, &templateServiceManyPongsServer{ServerStream: stream})
}

type TemplateService_ManyPongsServer interface {
	Send(*Pong) error
	grpc.ServerStream
}

type templateServiceManyPongsServer struct {
	grpc.ServerStream
}

func (x *templateServiceManyPongsServer) Send(m *Pong) error {
	return x.ServerStream.SendMsg(m)
}

func _TemplateService_ManyPingPongs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TemplateServiceServer).ManyPingPongs(&templateServiceManyPingPongsServer{ServerStream: stream})
}

type TemplateService_ManyPingPongsServer interface {
	Send(*Pong) error
	Recv() (*Ping, error)
	grpc.ServerStream
}

type templateServiceManyPingPongsServer struct {
	grpc.ServerStream
}

func (x *templateServiceManyPingPongsServer) Send(m *Pong) error {
	return x.ServerStream.SendMsg(m)
}

func (x *templateServiceManyPingPongsServer) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TemplateService_GetPaginatedExample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServiceServer).GetPaginatedExample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateService_GetPaginatedExample_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServiceServer).GetPaginatedExample(ctx, req.(*PaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TemplateService_ServiceDesc is the grpc.ServiceDesc for TemplateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemplateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TemplateService",
	HandlerType: (*TemplateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingPong",
			Handler:    _TemplateService_PingPong_Handler,
		},
		{
			MethodName: "GetPaginatedExample",
			Handler:    _TemplateService_GetPaginatedExample_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ManyPings",
			Handler:       _TemplateService_ManyPings_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ManyPongs",
			Handler:       _TemplateService_ManyPongs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ManyPingPongs",
			Handler:       _TemplateService_ManyPingPongs_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/api/grpc/proto/protofile.proto",
}
