// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: internal/api/grpc/proto/protofile.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SponsorshipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tier int32 `protobuf:"varint,2,opt,name=tier,proto3" json:"tier,omitempty"`
}

func (x *SponsorshipRequest) Reset() {
	*x = SponsorshipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SponsorshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SponsorshipRequest) ProtoMessage() {}

func (x *SponsorshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SponsorshipRequest.ProtoReflect.Descriptor instead.
func (*SponsorshipRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{0}
}

func (x *SponsorshipRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SponsorshipRequest) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

type SponsorshipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tier  int32                  `protobuf:"varint,2,opt,name=tier,proto3" json:"tier,omitempty"`
	Until *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=until,proto3" json:"until,omitempty"`
}

func (x *SponsorshipResponse) Reset() {
	*x = SponsorshipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SponsorshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SponsorshipResponse) ProtoMessage() {}

func (x *SponsorshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SponsorshipResponse.ProtoReflect.Descriptor instead.
func (*SponsorshipResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{1}
}

func (x *SponsorshipResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SponsorshipResponse) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *SponsorshipResponse) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

type GetRestaurantSponsorshipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRestaurantSponsorshipRequest) Reset() {
	*x = GetRestaurantSponsorshipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRestaurantSponsorshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantSponsorshipRequest) ProtoMessage() {}

func (x *GetRestaurantSponsorshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantSponsorshipRequest.ProtoReflect.Descriptor instead.
func (*GetRestaurantSponsorshipRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{2}
}

func (x *GetRestaurantSponsorshipRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRestaurantSponsorshipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Categories []string `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	OwnerId    int32    `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
}

func (x *GetRestaurantSponsorshipResponse) Reset() {
	*x = GetRestaurantSponsorshipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRestaurantSponsorshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantSponsorshipResponse) ProtoMessage() {}

func (x *GetRestaurantSponsorshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantSponsorshipResponse.ProtoReflect.Descriptor instead.
func (*GetRestaurantSponsorshipResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{3}
}

func (x *GetRestaurantSponsorshipResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetRestaurantSponsorshipResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GetRestaurantSponsorshipResponse) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

var File_internal_api_grpc_proto_protofile_proto protoreflect.FileDescriptor

var file_internal_api_grpc_proto_protofile_proto_rawDesc = []byte{
	0x0a, 0x27, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x38, 0x0a, 0x12, 0x53, 0x70, 0x6f, 0x6e, 0x73, 0x6f, 0x72, 0x73, 0x68, 0x69, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x65, 0x72, 0x22, 0x6b, 0x0a, 0x13, 0x53,
	0x70, 0x6f, 0x6e, 0x73, 0x6f, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x74, 0x69, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x05, 0x75, 0x6e, 0x74, 0x69, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x05, 0x75, 0x6e, 0x74, 0x69, 0x6c, 0x22, 0x31, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x53, 0x70, 0x6f, 0x6e, 0x73, 0x6f, 0x72,
	0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x6d, 0x0a, 0x20, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x53, 0x70, 0x6f, 0x6e,
	0x73, 0x6f, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12,
	0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x32, 0xb2, 0x01, 0x0a, 0x0e, 0x53,
	0x70, 0x6f, 0x6e, 0x73, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a,
	0x07, 0x53, 0x70, 0x6f, 0x6e, 0x73, 0x6f, 0x72, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x70, 0x6f, 0x6e, 0x73, 0x6f, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x6f, 0x6e,
	0x73, 0x6f, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x5e, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74,
	0x53, 0x70, 0x6f, 0x6e, 0x73, 0x6f, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x26, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e,
	0x74, 0x53, 0x70, 0x6f, 0x6e, 0x73, 0x6f, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x6f, 0x6e,
	0x73, 0x6f, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0x89, 0x01, 0x0a, 0x1a, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x54, 0x6f,
	0x53, 0x70, 0x6f, 0x6e, 0x73, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6b,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x53,
	0x70, 0x6f, 0x6e, 0x73, 0x6f, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x26, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74,
	0x53, 0x70, 0x6f, 0x6e, 0x73, 0x6f, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x53, 0x70, 0x6f, 0x6e, 0x73, 0x6f, 0x72, 0x73,
	0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2f,
	0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_api_grpc_proto_protofile_proto_rawDescOnce sync.Once
	file_internal_api_grpc_proto_protofile_proto_rawDescData = file_internal_api_grpc_proto_protofile_proto_rawDesc
)

func file_internal_api_grpc_proto_protofile_proto_rawDescGZIP() []byte {
	file_internal_api_grpc_proto_protofile_proto_rawDescOnce.Do(func() {
		file_internal_api_grpc_proto_protofile_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_api_grpc_proto_protofile_proto_rawDescData)
	})
	return file_internal_api_grpc_proto_protofile_proto_rawDescData
}

var file_internal_api_grpc_proto_protofile_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_api_grpc_proto_protofile_proto_goTypes = []interface{}{
	(*SponsorshipRequest)(nil),               // 0: proto.SponsorshipRequest
	(*SponsorshipResponse)(nil),              // 1: proto.SponsorshipResponse
	(*GetRestaurantSponsorshipRequest)(nil),  // 2: proto.GetRestaurantSponsorshipRequest
	(*GetRestaurantSponsorshipResponse)(nil), // 3: proto.GetRestaurantSponsorshipResponse
	(*timestamppb.Timestamp)(nil),            // 4: google.protobuf.Timestamp
}
var file_internal_api_grpc_proto_protofile_proto_depIdxs = []int32{
	4, // 0: proto.SponsorshipResponse.until:type_name -> google.protobuf.Timestamp
	0, // 1: proto.SponsorService.Sponsor:input_type -> proto.SponsorshipRequest
	2, // 2: proto.SponsorService.GetRestaurantSponsorship:input_type -> proto.GetRestaurantSponsorshipRequest
	2, // 3: proto.RestaurantToSponsorService.GetRestaurantSponsorship:input_type -> proto.GetRestaurantSponsorshipRequest
	1, // 4: proto.SponsorService.Sponsor:output_type -> proto.SponsorshipResponse
	1, // 5: proto.SponsorService.GetRestaurantSponsorship:output_type -> proto.SponsorshipResponse
	3, // 6: proto.RestaurantToSponsorService.GetRestaurantSponsorship:output_type -> proto.GetRestaurantSponsorshipResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_api_grpc_proto_protofile_proto_init() }
func file_internal_api_grpc_proto_protofile_proto_init() {
	if File_internal_api_grpc_proto_protofile_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_api_grpc_proto_protofile_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SponsorshipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_grpc_proto_protofile_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SponsorshipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_grpc_proto_protofile_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRestaurantSponsorshipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_grpc_proto_protofile_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRestaurantSponsorshipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_api_grpc_proto_protofile_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_api_grpc_proto_protofile_proto_goTypes,
		DependencyIndexes: file_internal_api_grpc_proto_protofile_proto_depIdxs,
		MessageInfos:      file_internal_api_grpc_proto_protofile_proto_msgTypes,
	}.Build()
	File_internal_api_grpc_proto_protofile_proto = out.File
	file_internal_api_grpc_proto_protofile_proto_rawDesc = nil
	file_internal_api_grpc_proto_protofile_proto_goTypes = nil
	file_internal_api_grpc_proto_protofile_proto_depIdxs = nil
}
