// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/api/grpc/proto/protofile.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRegistrationEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRegistrationEmailRequest) Reset() {
	*x = SendRegistrationEmailRequest{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRegistrationEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRegistrationEmailRequest) ProtoMessage() {}

func (x *SendRegistrationEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRegistrationEmailRequest.ProtoReflect.Descriptor instead.
func (*SendRegistrationEmailRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{0}
}

func (x *SendRegistrationEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendRegistrationEmailRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SendRegistrationEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRegistrationEmailResponse) Reset() {
	*x = SendRegistrationEmailResponse{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRegistrationEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRegistrationEmailResponse) ProtoMessage() {}

func (x *SendRegistrationEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRegistrationEmailResponse.ProtoReflect.Descriptor instead.
func (*SendRegistrationEmailResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{1}
}

type SendReceiptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Receipts      []*Receipt             `protobuf:"bytes,2,rep,name=receipts,proto3" json:"receipts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendReceiptsRequest) Reset() {
	*x = SendReceiptsRequest{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendReceiptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReceiptsRequest) ProtoMessage() {}

func (x *SendReceiptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReceiptsRequest.ProtoReflect.Descriptor instead.
func (*SendReceiptsRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{2}
}

func (x *SendReceiptsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendReceiptsRequest) GetReceipts() []*Receipt {
	if x != nil {
		return x.Receipts
	}
	return nil
}

type SendReceiptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendReceiptsResponse) Reset() {
	*x = SendReceiptsResponse{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendReceiptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReceiptsResponse) ProtoMessage() {}

func (x *SendReceiptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReceiptsResponse.ProtoReflect.Descriptor instead.
func (*SendReceiptsResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{3}
}

type Receipt struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Amount               float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentDescription   string                 `protobuf:"bytes,2,opt,name=payment_description,json=paymentDescription,proto3" json:"payment_description,omitempty"`
	CurrentPaymentStatus string                 `protobuf:"bytes,3,opt,name=current_payment_status,json=currentPaymentStatus,proto3" json:"current_payment_status,omitempty"`
	PaymentType          string                 `protobuf:"bytes,4,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{4}
}

func (x *Receipt) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Receipt) GetPaymentDescription() string {
	if x != nil {
		return x.PaymentDescription
	}
	return ""
}

func (x *Receipt) GetCurrentPaymentStatus() string {
	if x != nil {
		return x.CurrentPaymentStatus
	}
	return ""
}

func (x *Receipt) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *Receipt) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_internal_api_grpc_proto_protofile_proto protoreflect.FileDescriptor

const file_internal_api_grpc_proto_protofile_proto_rawDesc = "" +
	"\n" +
	"'internal/api/grpc/proto/protofile.proto\x12\fnotification\x1a\x1fgoogle/protobuf/timestamp.proto\"P\n" +
	"\x1cSendRegistrationEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\x1f\n" +
	"\x1dSendRegistrationEmailResponse\"^\n" +
	"\x13SendReceiptsRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x121\n" +
	"\breceipts\x18\x02 \x03(\v2\x15.notification.ReceiptR\breceipts\"\x16\n" +
	"\x14SendReceiptsResponse\"\xe6\x01\n" +
	"\aReceipt\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12/\n" +
	"\x13payment_description\x18\x02 \x01(\tR\x12paymentDescription\x124\n" +
	"\x16current_payment_status\x18\x03 \x01(\tR\x14currentPaymentStatus\x12!\n" +
	"\fpayment_type\x18\x04 \x01(\tR\vpaymentType\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xde\x01\n" +
	"\x13NotificationService\x12p\n" +
	"\x15SendRegistrationEmail\x12*.notification.SendRegistrationEmailRequest\x1a+.notification.SendRegistrationEmailResponse\x12U\n" +
	"\fSendReceipts\x12!.notification.SendReceiptsRequest\x1a\".notification.SendReceiptsResponseB\bZ\x06/pb;pbb\x06proto3"

var (
	file_internal_api_grpc_proto_protofile_proto_rawDescOnce sync.Once
	file_internal_api_grpc_proto_protofile_proto_rawDescData []byte
)

func file_internal_api_grpc_proto_protofile_proto_rawDescGZIP() []byte {
	file_internal_api_grpc_proto_protofile_proto_rawDescOnce.Do(func() {
		file_internal_api_grpc_proto_protofile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_grpc_proto_protofile_proto_rawDesc), len(file_internal_api_grpc_proto_protofile_proto_rawDesc)))
	})
	return file_internal_api_grpc_proto_protofile_proto_rawDescData
}

var file_internal_api_grpc_proto_protofile_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_api_grpc_proto_protofile_proto_goTypes = []any{
	(*SendRegistrationEmailRequest)(nil),  // 0: notification.SendRegistrationEmailRequest
	(*SendRegistrationEmailResponse)(nil), // 1: notification.SendRegistrationEmailResponse
	(*SendReceiptsRequest)(nil),           // 2: notification.SendReceiptsRequest
	(*SendReceiptsResponse)(nil),          // 3: notification.SendReceiptsResponse
	(*Receipt)(nil),                       // 4: notification.Receipt
	(*timestamppb.Timestamp)(nil),         // 5: google.protobuf.Timestamp
}
var file_internal_api_grpc_proto_protofile_proto_depIdxs = []int32{
	4, // 0: notification.SendReceiptsRequest.receipts:type_name -> notification.Receipt
	5, // 1: notification.Receipt.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: notification.NotificationService.SendRegistrationEmail:input_type -> notification.SendRegistrationEmailRequest
	2, // 3: notification.NotificationService.SendReceipts:input_type -> notification.SendReceiptsRequest
	1, // 4: notification.NotificationService.SendRegistrationEmail:output_type -> notification.SendRegistrationEmailResponse
	3, // 5: notification.NotificationService.SendReceipts:output_type -> notification.SendReceiptsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_api_grpc_proto_protofile_proto_init() }
func file_internal_api_grpc_proto_protofile_proto_init() {
	if File_internal_api_grpc_proto_protofile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_grpc_proto_protofile_proto_rawDesc), len(file_internal_api_grpc_proto_protofile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_grpc_proto_protofile_proto_goTypes,
		DependencyIndexes: file_internal_api_grpc_proto_protofile_proto_depIdxs,
		MessageInfos:      file_internal_api_grpc_proto_protofile_proto_msgTypes,
	}.Build()
	File_internal_api_grpc_proto_protofile_proto = out.File
	file_internal_api_grpc_proto_protofile_proto_goTypes = nil
	file_internal_api_grpc_proto_protofile_proto_depIdxs = nil
}
