// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: internal/api/grpc/proto/protofile.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthToNotificationService_SendRegistrationEmail_FullMethodName = "/notification.AuthToNotificationService/SendRegistrationEmail"
)

// AuthToNotificationServiceClient is the client API for AuthToNotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthToNotificationService defines the gRPC service for sending notifications related to user authentication.
type AuthToNotificationServiceClient interface {
	// SendRegistrationEmail sends a registration email to the specified username.
	SendRegistrationEmail(ctx context.Context, in *SendRegistrationEmailRequest, opts ...grpc.CallOption) (*SendRegistrationEmailResponse, error)
}

type authToNotificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthToNotificationServiceClient(cc grpc.ClientConnInterface) AuthToNotificationServiceClient {
	return &authToNotificationServiceClient{cc}
}

func (c *authToNotificationServiceClient) SendRegistrationEmail(ctx context.Context, in *SendRegistrationEmailRequest, opts ...grpc.CallOption) (*SendRegistrationEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendRegistrationEmailResponse)
	err := c.cc.Invoke(ctx, AuthToNotificationService_SendRegistrationEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthToNotificationServiceServer is the server API for AuthToNotificationService service.
// All implementations must embed UnimplementedAuthToNotificationServiceServer
// for forward compatibility.
//
// AuthToNotificationService defines the gRPC service for sending notifications related to user authentication.
type AuthToNotificationServiceServer interface {
	// SendRegistrationEmail sends a registration email to the specified username.
	SendRegistrationEmail(context.Context, *SendRegistrationEmailRequest) (*SendRegistrationEmailResponse, error)
	mustEmbedUnimplementedAuthToNotificationServiceServer()
}

// UnimplementedAuthToNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthToNotificationServiceServer struct{}

func (UnimplementedAuthToNotificationServiceServer) SendRegistrationEmail(context.Context, *SendRegistrationEmailRequest) (*SendRegistrationEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendRegistrationEmail not implemented")
}
func (UnimplementedAuthToNotificationServiceServer) mustEmbedUnimplementedAuthToNotificationServiceServer() {
}
func (UnimplementedAuthToNotificationServiceServer) testEmbeddedByValue() {}

// UnsafeAuthToNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthToNotificationServiceServer will
// result in compilation errors.
type UnsafeAuthToNotificationServiceServer interface {
	mustEmbedUnimplementedAuthToNotificationServiceServer()
}

func RegisterAuthToNotificationServiceServer(s grpc.ServiceRegistrar, srv AuthToNotificationServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthToNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthToNotificationService_ServiceDesc, srv)
}

func _AuthToNotificationService_SendRegistrationEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRegistrationEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthToNotificationServiceServer).SendRegistrationEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthToNotificationService_SendRegistrationEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthToNotificationServiceServer).SendRegistrationEmail(ctx, req.(*SendRegistrationEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthToNotificationService_ServiceDesc is the grpc.ServiceDesc for AuthToNotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthToNotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.AuthToNotificationService",
	HandlerType: (*AuthToNotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRegistrationEmail",
			Handler:    _AuthToNotificationService_SendRegistrationEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/grpc/proto/protofile.proto",
}

const (
	PaymentToNotificationService_SendReceipts_FullMethodName = "/notification.PaymentToNotificationService/SendReceipts"
)

// PaymentToNotificationServiceClient is the client API for PaymentToNotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PaymentToNotificationService defines the gRPC service for sending notifications related to payments.
type PaymentToNotificationServiceClient interface {
	// SendReceipts sends a list of receipts to the appropriate recipients.
	SendReceipts(ctx context.Context, in *SendReceiptsRequest, opts ...grpc.CallOption) (*SendReceiptsResponse, error)
}

type paymentToNotificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentToNotificationServiceClient(cc grpc.ClientConnInterface) PaymentToNotificationServiceClient {
	return &paymentToNotificationServiceClient{cc}
}

func (c *paymentToNotificationServiceClient) SendReceipts(ctx context.Context, in *SendReceiptsRequest, opts ...grpc.CallOption) (*SendReceiptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendReceiptsResponse)
	err := c.cc.Invoke(ctx, PaymentToNotificationService_SendReceipts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentToNotificationServiceServer is the server API for PaymentToNotificationService service.
// All implementations must embed UnimplementedPaymentToNotificationServiceServer
// for forward compatibility.
//
// PaymentToNotificationService defines the gRPC service for sending notifications related to payments.
type PaymentToNotificationServiceServer interface {
	// SendReceipts sends a list of receipts to the appropriate recipients.
	SendReceipts(context.Context, *SendReceiptsRequest) (*SendReceiptsResponse, error)
	mustEmbedUnimplementedPaymentToNotificationServiceServer()
}

// UnimplementedPaymentToNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentToNotificationServiceServer struct{}

func (UnimplementedPaymentToNotificationServiceServer) SendReceipts(context.Context, *SendReceiptsRequest) (*SendReceiptsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendReceipts not implemented")
}
func (UnimplementedPaymentToNotificationServiceServer) mustEmbedUnimplementedPaymentToNotificationServiceServer() {
}
func (UnimplementedPaymentToNotificationServiceServer) testEmbeddedByValue() {}

// UnsafePaymentToNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentToNotificationServiceServer will
// result in compilation errors.
type UnsafePaymentToNotificationServiceServer interface {
	mustEmbedUnimplementedPaymentToNotificationServiceServer()
}

func RegisterPaymentToNotificationServiceServer(s grpc.ServiceRegistrar, srv PaymentToNotificationServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentToNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentToNotificationService_ServiceDesc, srv)
}

func _PaymentToNotificationService_SendReceipts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendReceiptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentToNotificationServiceServer).SendReceipts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentToNotificationService_SendReceipts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentToNotificationServiceServer).SendReceipts(ctx, req.(*SendReceiptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentToNotificationService_ServiceDesc is the grpc.ServiceDesc for PaymentToNotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentToNotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.PaymentToNotificationService",
	HandlerType: (*PaymentToNotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendReceipts",
			Handler:    _PaymentToNotificationService_SendReceipts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/grpc/proto/protofile.proto",
}
