receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

  filter/drop_health_checks:
    error_mode: ignore
    traces:
      span:
        - 'attributes["rpc.method"] == "Check" and attributes["rpc.service"] == "grpc.health.v1.Health"'
        - 'name == "grpc.health.v1.Health/Check"'

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

  debug:
    verbosity: detailed

  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter/drop_health_checks, batch]
      exporters: [otlp, debug]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki, debug]