name: booking
image: europe-southwest1-docker.pkg.dev/mrfood-490623/mrfood-repo/booking:v1.0.0
port: 50053

service:
  type: ClusterIP

env:
  secrets:
    DB_PASS: bookingsecret
  config:
    APP_SERVER_PORT: 50053
    DB_NAME: mrfood_booking
    DB_USER: booking
    DB_HOST: 127.0.0.1
    DB_PORT: 5434
    APP_LOG_LEVEL: debug
    RESTAURANT_GRPC_ADDR: "restaurant:50052"
    PAYMENT_GRPC_ADDR: "payment:50057"

cloudsql:
  instance: mrfood-booking-pg