name: booking
image: europe-southwest1-docker.pkg.dev/mrfood-490623/mrfood-repo/booking:v1.0.1
port: 50053

service:
  type: ClusterIP

env:
  secrets:
    BOOKING_POSTGRES_PASSWORD: mrfood_booking_secret
  config:
    BOOKING_SERVER_PORT: 50053
    BOOKING_POSTGRES_DB: mrfood_booking
    BOOKING_POSTGRES_USER: mrfood_booking_user
    POSTGRES_HOST: 127.0.0.1
    POSTGRES_PORT: 5432
    POSTGRES_MIN_CONNS: 4
    POSTGRES_MAX_CONNS: 20
    POSTGRES_MAX_CONN_LIFETIME: 15m
    POSTGRES_HEALTH_CHECK_PERIOD: 1m
    APP_LOG_LEVEL: debug
    RESTAURANT_GRPC_ADDR: "restaurant:80"
    PAYMENT_GRPC_ADDR: "payment:80"

cloudsql:
  instance: mrfood-490623:europe-southwest1:mrfood-booking-pg
