name: sponsor
image: europe-southwest1-docker.pkg.dev/mrfood-490623/mrfood-repo/sponsor:v1.0.1
port: 50054

service:
  type: ClusterIP

env:
  secrets:
    DB_PASS: mrfood_sponsor_secret
  config:
    APP_SERVER_PORT: 50054
    SPONSOR_DB_PORT: 5432
    DB_NAME: mrfood_sponsor
    DB_USER: mrfood_sponsor_user
    DB_HOST: 127.0.0.1
    APP_LOG_LEVEL: debug
    RESTAURANT_GRPC_ADDR: "restaurant:50052"
    PAYMENT_GRPC_ADDR: "payment:50057"

cloudsql:
  instance: mrfood-490623:europe-southwest1:mrfood-sponsor-pg
