// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: internal/api/grpc/proto/protofile.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestaurantStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int32                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	AverageRating float64                `protobuf:"fixed64,2,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	ReviewCount   int32                  `protobuf:"varint,3,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantStats) Reset() {
	*x = RestaurantStats{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantStats) ProtoMessage() {}

func (x *RestaurantStats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantStats.ProtoReflect.Descriptor instead.
func (*RestaurantStats) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{0}
}

func (x *RestaurantStats) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *RestaurantStats) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *RestaurantStats) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

type GetRestaurantStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int32                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantStatsRequest) Reset() {
	*x = GetRestaurantStatsRequest{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantStatsRequest) ProtoMessage() {}

func (x *GetRestaurantStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantStatsRequest.ProtoReflect.Descriptor instead.
func (*GetRestaurantStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{1}
}

func (x *GetRestaurantStatsRequest) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

type GetRestaurantStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RestaurantStats *RestaurantStats       `protobuf:"bytes,1,opt,name=restaurant_stats,json=restaurantStats,proto3" json:"restaurant_stats,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRestaurantStatsResponse) Reset() {
	*x = GetRestaurantStatsResponse{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantStatsResponse) ProtoMessage() {}

func (x *GetRestaurantStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantStatsResponse.ProtoReflect.Descriptor instead.
func (*GetRestaurantStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{2}
}

func (x *GetRestaurantStatsResponse) GetRestaurantStats() *RestaurantStats {
	if x != nil {
		return x.RestaurantStats
	}
	return nil
}

type WorkingHoursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int32                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	TimeStart     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkingHoursRequest) Reset() {
	*x = WorkingHoursRequest{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkingHoursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkingHoursRequest) ProtoMessage() {}

func (x *WorkingHoursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkingHoursRequest.ProtoReflect.Descriptor instead.
func (*WorkingHoursRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{3}
}

func (x *WorkingHoursRequest) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *WorkingHoursRequest) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

type WorkingHoursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int32                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	WorkingHours  *TimeRange             `protobuf:"bytes,2,opt,name=working_hours,json=workingHours,proto3" json:"working_hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkingHoursResponse) Reset() {
	*x = WorkingHoursResponse{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkingHoursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkingHoursResponse) ProtoMessage() {}

func (x *WorkingHoursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkingHoursResponse.ProtoReflect.Descriptor instead.
func (*WorkingHoursResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{4}
}

func (x *WorkingHoursResponse) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *WorkingHoursResponse) GetWorkingHours() *TimeRange {
	if x != nil {
		return x.WorkingHours
	}
	return nil
}

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeStart     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	TimeEnd       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{5}
}

func (x *TimeRange) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

func (x *TimeRange) GetTimeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeEnd
	}
	return nil
}

type GetRestaurantDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantDetailsRequest) Reset() {
	*x = GetRestaurantDetailsRequest{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantDetailsRequest) ProtoMessage() {}

func (x *GetRestaurantDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetRestaurantDetailsRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{6}
}

func (x *GetRestaurantDetailsRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRestaurantDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurant    *RestaurantDetails     `protobuf:"bytes,1,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantDetailsResponse) Reset() {
	*x = GetRestaurantDetailsResponse{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantDetailsResponse) ProtoMessage() {}

func (x *GetRestaurantDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetRestaurantDetailsResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{7}
}

func (x *GetRestaurantDetailsResponse) GetRestaurant() *RestaurantDetails {
	if x != nil {
		return x.Restaurant
	}
	return nil
}

type CreateRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	WorkingHours  []string               `protobuf:"bytes,5,rep,name=working_hours,json=workingHours,proto3" json:"working_hours,omitempty"`
	Categories    []string               `protobuf:"bytes,6,rep,name=categories,proto3" json:"categories,omitempty"`
	MaxSlots      int32                  `protobuf:"varint,7,opt,name=max_slots,json=maxSlots,proto3" json:"max_slots,omitempty"`
	HasMedia      bool                   `protobuf:"varint,8,opt,name=has_media,json=hasMedia,proto3" json:"has_media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRestaurantRequest) Reset() {
	*x = CreateRestaurantRequest{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRestaurantRequest) ProtoMessage() {}

func (x *CreateRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRestaurantRequest.ProtoReflect.Descriptor instead.
func (*CreateRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{8}
}

func (x *CreateRestaurantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRestaurantRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateRestaurantRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreateRestaurantRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateRestaurantRequest) GetWorkingHours() []string {
	if x != nil {
		return x.WorkingHours
	}
	return nil
}

func (x *CreateRestaurantRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *CreateRestaurantRequest) GetMaxSlots() int32 {
	if x != nil {
		return x.MaxSlots
	}
	return 0
}

func (x *CreateRestaurantRequest) GetHasMedia() bool {
	if x != nil {
		return x.HasMedia
	}
	return false
}

type CreateRestaurantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int32                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	PresignedUrl  *string                `protobuf:"bytes,2,opt,name=presigned_url,json=presignedUrl,proto3,oneof" json:"presigned_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRestaurantResponse) Reset() {
	*x = CreateRestaurantResponse{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRestaurantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRestaurantResponse) ProtoMessage() {}

func (x *CreateRestaurantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRestaurantResponse.ProtoReflect.Descriptor instead.
func (*CreateRestaurantResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{9}
}

func (x *CreateRestaurantResponse) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *CreateRestaurantResponse) GetPresignedUrl() string {
	if x != nil && x.PresignedUrl != nil {
		return *x.PresignedUrl
	}
	return ""
}

type UpdateRestaurantRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            int32                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float64                  `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                  `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address       string                   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	WorkingHours  []*timestamppb.Timestamp `protobuf:"bytes,6,rep,name=working_hours,json=workingHours,proto3" json:"working_hours,omitempty"`
	Categories    []string                 `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	MaxSlots      int32                    `protobuf:"varint,8,opt,name=max_slots,json=maxSlots,proto3" json:"max_slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRestaurantRequest) Reset() {
	*x = UpdateRestaurantRequest{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRestaurantRequest) ProtoMessage() {}

func (x *UpdateRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRestaurantRequest.ProtoReflect.Descriptor instead.
func (*UpdateRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateRestaurantRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRestaurantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRestaurantRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateRestaurantRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UpdateRestaurantRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateRestaurantRequest) GetWorkingHours() []*timestamppb.Timestamp {
	if x != nil {
		return x.WorkingHours
	}
	return nil
}

func (x *UpdateRestaurantRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *UpdateRestaurantRequest) GetMaxSlots() int32 {
	if x != nil {
		return x.MaxSlots
	}
	return 0
}

type UpdateRestaurantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurant    *RestaurantDetails     `protobuf:"bytes,1,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRestaurantResponse) Reset() {
	*x = UpdateRestaurantResponse{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRestaurantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRestaurantResponse) ProtoMessage() {}

func (x *UpdateRestaurantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRestaurantResponse.ProtoReflect.Descriptor instead.
func (*UpdateRestaurantResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateRestaurantResponse) GetRestaurant() *RestaurantDetails {
	if x != nil {
		return x.Restaurant
	}
	return nil
}

type RestaurantDetails struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            int32                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float64                  `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                  `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address       string                   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	WorkingHours  []*timestamppb.Timestamp `protobuf:"bytes,6,rep,name=working_hours,json=workingHours,proto3" json:"working_hours,omitempty"`
	Categories    []string                 `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	MediaUrl      *string                  `protobuf:"bytes,8,opt,name=media_url,json=mediaUrl,proto3,oneof" json:"media_url,omitempty"`
	MaxSlots      int32                    `protobuf:"varint,9,opt,name=max_slots,json=maxSlots,proto3" json:"max_slots,omitempty"`
	OwnerId       int32                    `protobuf:"varint,10,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerName     string                   `protobuf:"bytes,11,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	SponsorTier   int32                    `protobuf:"varint,12,opt,name=sponsor_tier,json=sponsorTier,proto3" json:"sponsor_tier,omitempty"`
	AverageRating float64                  `protobuf:"fixed64,13,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	ReviewCount   int32                    `protobuf:"varint,14,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantDetails) Reset() {
	*x = RestaurantDetails{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantDetails) ProtoMessage() {}

func (x *RestaurantDetails) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantDetails.ProtoReflect.Descriptor instead.
func (*RestaurantDetails) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{12}
}

func (x *RestaurantDetails) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RestaurantDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestaurantDetails) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RestaurantDetails) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *RestaurantDetails) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RestaurantDetails) GetWorkingHours() []*timestamppb.Timestamp {
	if x != nil {
		return x.WorkingHours
	}
	return nil
}

func (x *RestaurantDetails) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *RestaurantDetails) GetMediaUrl() string {
	if x != nil && x.MediaUrl != nil {
		return *x.MediaUrl
	}
	return ""
}

func (x *RestaurantDetails) GetMaxSlots() int32 {
	if x != nil {
		return x.MaxSlots
	}
	return 0
}

func (x *RestaurantDetails) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *RestaurantDetails) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *RestaurantDetails) GetSponsorTier() int32 {
	if x != nil {
		return x.SponsorTier
	}
	return 0
}

func (x *RestaurantDetails) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *RestaurantDetails) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

type CompareRestaurantDetailsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId_1 int32                  `protobuf:"varint,1,opt,name=restaurant_id_1,json=restaurantId1,proto3" json:"restaurant_id_1,omitempty"`
	RestaurantId_2 int32                  `protobuf:"varint,2,opt,name=restaurant_id_2,json=restaurantId2,proto3" json:"restaurant_id_2,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompareRestaurantDetailsRequest) Reset() {
	*x = CompareRestaurantDetailsRequest{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareRestaurantDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareRestaurantDetailsRequest) ProtoMessage() {}

func (x *CompareRestaurantDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareRestaurantDetailsRequest.ProtoReflect.Descriptor instead.
func (*CompareRestaurantDetailsRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{13}
}

func (x *CompareRestaurantDetailsRequest) GetRestaurantId_1() int32 {
	if x != nil {
		return x.RestaurantId_1
	}
	return 0
}

func (x *CompareRestaurantDetailsRequest) GetRestaurantId_2() int32 {
	if x != nil {
		return x.RestaurantId_2
	}
	return 0
}

type CompareRestaurantDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurant1   *RestaurantDetails     `protobuf:"bytes,1,opt,name=restaurant1,proto3" json:"restaurant1,omitempty"`
	Restaurant2   *RestaurantDetails     `protobuf:"bytes,2,opt,name=restaurant2,proto3" json:"restaurant2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareRestaurantDetailsResponse) Reset() {
	*x = CompareRestaurantDetailsResponse{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareRestaurantDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareRestaurantDetailsResponse) ProtoMessage() {}

func (x *CompareRestaurantDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareRestaurantDetailsResponse.ProtoReflect.Descriptor instead.
func (*CompareRestaurantDetailsResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{14}
}

func (x *CompareRestaurantDetailsResponse) GetRestaurant1() *RestaurantDetails {
	if x != nil {
		return x.Restaurant1
	}
	return nil
}

func (x *CompareRestaurantDetailsResponse) GetRestaurant2() *RestaurantDetails {
	if x != nil {
		return x.Restaurant2
	}
	return nil
}

var File_internal_api_grpc_proto_protofile_proto protoreflect.FileDescriptor

const file_internal_api_grpc_proto_protofile_proto_rawDesc = "" +
	"\n" +
	"'internal/api/grpc/proto/protofile.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x01\n" +
	"\x0fRestaurantStats\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x05R\frestaurantId\x12%\n" +
	"\x0eaverage_rating\x18\x02 \x01(\x01R\raverageRating\x12!\n" +
	"\freview_count\x18\x03 \x01(\x05R\vreviewCount\"@\n" +
	"\x19GetRestaurantStatsRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x05R\frestaurantId\"_\n" +
	"\x1aGetRestaurantStatsResponse\x12A\n" +
	"\x10restaurant_stats\x18\x01 \x01(\v2\x16.proto.RestaurantStatsR\x0frestaurantStats\"u\n" +
	"\x13WorkingHoursRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x05R\frestaurantId\x129\n" +
	"\n" +
	"time_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\"r\n" +
	"\x14WorkingHoursResponse\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x05R\frestaurantId\x125\n" +
	"\rworking_hours\x18\x02 \x01(\v2\x10.proto.TimeRangeR\fworkingHours\"}\n" +
	"\tTimeRange\x129\n" +
	"\n" +
	"time_start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\x125\n" +
	"\btime_end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\atimeEnd\"-\n" +
	"\x1bGetRestaurantDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"X\n" +
	"\x1cGetRestaurantDetailsResponse\x128\n" +
	"\n" +
	"restaurant\x18\x01 \x01(\v2\x18.proto.RestaurantDetailsR\n" +
	"restaurant\"\x80\x02\n" +
	"\x17CreateRestaurantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12#\n" +
	"\rworking_hours\x18\x05 \x03(\tR\fworkingHours\x12\x1e\n" +
	"\n" +
	"categories\x18\x06 \x03(\tR\n" +
	"categories\x12\x1b\n" +
	"\tmax_slots\x18\a \x01(\x05R\bmaxSlots\x12\x1b\n" +
	"\thas_media\x18\b \x01(\bR\bhasMedia\"{\n" +
	"\x18CreateRestaurantResponse\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x05R\frestaurantId\x12(\n" +
	"\rpresigned_url\x18\x02 \x01(\tH\x00R\fpresignedUrl\x88\x01\x01B\x10\n" +
	"\x0e_presigned_url\"\x8f\x02\n" +
	"\x17UpdateRestaurantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12?\n" +
	"\rworking_hours\x18\x06 \x03(\v2\x1a.google.protobuf.TimestampR\fworkingHours\x12\x1e\n" +
	"\n" +
	"categories\x18\a \x03(\tR\n" +
	"categories\x12\x1b\n" +
	"\tmax_slots\x18\b \x01(\x05R\bmaxSlots\"T\n" +
	"\x18UpdateRestaurantResponse\x128\n" +
	"\n" +
	"restaurant\x18\x01 \x01(\v2\x18.proto.RestaurantDetailsR\n" +
	"restaurant\"\xe0\x03\n" +
	"\x11RestaurantDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12?\n" +
	"\rworking_hours\x18\x06 \x03(\v2\x1a.google.protobuf.TimestampR\fworkingHours\x12\x1e\n" +
	"\n" +
	"categories\x18\a \x03(\tR\n" +
	"categories\x12 \n" +
	"\tmedia_url\x18\b \x01(\tH\x00R\bmediaUrl\x88\x01\x01\x12\x1b\n" +
	"\tmax_slots\x18\t \x01(\x05R\bmaxSlots\x12\x19\n" +
	"\bowner_id\x18\n" +
	" \x01(\x05R\aownerId\x12\x1d\n" +
	"\n" +
	"owner_name\x18\v \x01(\tR\townerName\x12!\n" +
	"\fsponsor_tier\x18\f \x01(\x05R\vsponsorTier\x12%\n" +
	"\x0eaverage_rating\x18\r \x01(\x01R\raverageRating\x12!\n" +
	"\freview_count\x18\x0e \x01(\x05R\vreviewCountB\f\n" +
	"\n" +
	"_media_url\"q\n" +
	"\x1fCompareRestaurantDetailsRequest\x12&\n" +
	"\x0frestaurant_id_1\x18\x01 \x01(\x05R\rrestaurantId1\x12&\n" +
	"\x0frestaurant_id_2\x18\x02 \x01(\x05R\rrestaurantId2\"\x9a\x01\n" +
	" CompareRestaurantDetailsResponse\x12:\n" +
	"\vrestaurant1\x18\x01 \x01(\v2\x18.proto.RestaurantDetailsR\vrestaurant1\x12:\n" +
	"\vrestaurant2\x18\x02 \x01(\v2\x18.proto.RestaurantDetailsR\vrestaurant22\x8b\x03\n" +
	"\x11RestaurantService\x12_\n" +
	"\x14GetRestaurantDetails\x12\".proto.GetRestaurantDetailsRequest\x1a#.proto.GetRestaurantDetailsResponse\x12S\n" +
	"\x10CreateRestaurant\x12\x1e.proto.CreateRestaurantRequest\x1a\x1f.proto.CreateRestaurantResponse\x12S\n" +
	"\x10UpdateRestaurant\x12\x1e.proto.UpdateRestaurantRequest\x1a\x1f.proto.UpdateRestaurantResponse\x12k\n" +
	"\x18CompareRestaurantDetails\x12&.proto.CompareRestaurantDetailsRequest\x1a'.proto.CompareRestaurantDetailsResponse2h\n" +
	"\x1aRestaurantToBookingService\x12J\n" +
	"\x0fGetWorkingHours\x12\x1a.proto.WorkingHoursRequest\x1a\x1b.proto.WorkingHoursResponse2v\n" +
	"\x19RestaurantToReviewService\x12Y\n" +
	"\x12GetRestaurantStats\x12 .proto.GetRestaurantStatsRequest\x1a!.proto.GetRestaurantStatsResponseB\bZ\x06/pb;pbb\x06proto3"

var (
	file_internal_api_grpc_proto_protofile_proto_rawDescOnce sync.Once
	file_internal_api_grpc_proto_protofile_proto_rawDescData []byte
)

func file_internal_api_grpc_proto_protofile_proto_rawDescGZIP() []byte {
	file_internal_api_grpc_proto_protofile_proto_rawDescOnce.Do(func() {
		file_internal_api_grpc_proto_protofile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_grpc_proto_protofile_proto_rawDesc), len(file_internal_api_grpc_proto_protofile_proto_rawDesc)))
	})
	return file_internal_api_grpc_proto_protofile_proto_rawDescData
}

var file_internal_api_grpc_proto_protofile_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_api_grpc_proto_protofile_proto_goTypes = []any{
	(*RestaurantStats)(nil),                  // 0: proto.RestaurantStats
	(*GetRestaurantStatsRequest)(nil),        // 1: proto.GetRestaurantStatsRequest
	(*GetRestaurantStatsResponse)(nil),       // 2: proto.GetRestaurantStatsResponse
	(*WorkingHoursRequest)(nil),              // 3: proto.WorkingHoursRequest
	(*WorkingHoursResponse)(nil),             // 4: proto.WorkingHoursResponse
	(*TimeRange)(nil),                        // 5: proto.TimeRange
	(*GetRestaurantDetailsRequest)(nil),      // 6: proto.GetRestaurantDetailsRequest
	(*GetRestaurantDetailsResponse)(nil),     // 7: proto.GetRestaurantDetailsResponse
	(*CreateRestaurantRequest)(nil),          // 8: proto.CreateRestaurantRequest
	(*CreateRestaurantResponse)(nil),         // 9: proto.CreateRestaurantResponse
	(*UpdateRestaurantRequest)(nil),          // 10: proto.UpdateRestaurantRequest
	(*UpdateRestaurantResponse)(nil),         // 11: proto.UpdateRestaurantResponse
	(*RestaurantDetails)(nil),                // 12: proto.RestaurantDetails
	(*CompareRestaurantDetailsRequest)(nil),  // 13: proto.CompareRestaurantDetailsRequest
	(*CompareRestaurantDetailsResponse)(nil), // 14: proto.CompareRestaurantDetailsResponse
	(*timestamppb.Timestamp)(nil),            // 15: google.protobuf.Timestamp
}
var file_internal_api_grpc_proto_protofile_proto_depIdxs = []int32{
	0,  // 0: proto.GetRestaurantStatsResponse.restaurant_stats:type_name -> proto.RestaurantStats
	15, // 1: proto.WorkingHoursRequest.time_start:type_name -> google.protobuf.Timestamp
	5,  // 2: proto.WorkingHoursResponse.working_hours:type_name -> proto.TimeRange
	15, // 3: proto.TimeRange.time_start:type_name -> google.protobuf.Timestamp
	15, // 4: proto.TimeRange.time_end:type_name -> google.protobuf.Timestamp
	12, // 5: proto.GetRestaurantDetailsResponse.restaurant:type_name -> proto.RestaurantDetails
	15, // 6: proto.UpdateRestaurantRequest.working_hours:type_name -> google.protobuf.Timestamp
	12, // 7: proto.UpdateRestaurantResponse.restaurant:type_name -> proto.RestaurantDetails
	15, // 8: proto.RestaurantDetails.working_hours:type_name -> google.protobuf.Timestamp
	12, // 9: proto.CompareRestaurantDetailsResponse.restaurant1:type_name -> proto.RestaurantDetails
	12, // 10: proto.CompareRestaurantDetailsResponse.restaurant2:type_name -> proto.RestaurantDetails
	6,  // 11: proto.RestaurantService.GetRestaurantDetails:input_type -> proto.GetRestaurantDetailsRequest
	8,  // 12: proto.RestaurantService.CreateRestaurant:input_type -> proto.CreateRestaurantRequest
	10, // 13: proto.RestaurantService.UpdateRestaurant:input_type -> proto.UpdateRestaurantRequest
	13, // 14: proto.RestaurantService.CompareRestaurantDetails:input_type -> proto.CompareRestaurantDetailsRequest
	3,  // 15: proto.RestaurantToBookingService.GetWorkingHours:input_type -> proto.WorkingHoursRequest
	1,  // 16: proto.RestaurantToReviewService.GetRestaurantStats:input_type -> proto.GetRestaurantStatsRequest
	7,  // 17: proto.RestaurantService.GetRestaurantDetails:output_type -> proto.GetRestaurantDetailsResponse
	9,  // 18: proto.RestaurantService.CreateRestaurant:output_type -> proto.CreateRestaurantResponse
	11, // 19: proto.RestaurantService.UpdateRestaurant:output_type -> proto.UpdateRestaurantResponse
	14, // 20: proto.RestaurantService.CompareRestaurantDetails:output_type -> proto.CompareRestaurantDetailsResponse
	4,  // 21: proto.RestaurantToBookingService.GetWorkingHours:output_type -> proto.WorkingHoursResponse
	2,  // 22: proto.RestaurantToReviewService.GetRestaurantStats:output_type -> proto.GetRestaurantStatsResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_api_grpc_proto_protofile_proto_init() }
func file_internal_api_grpc_proto_protofile_proto_init() {
	if File_internal_api_grpc_proto_protofile_proto != nil {
		return
	}
	file_internal_api_grpc_proto_protofile_proto_msgTypes[9].OneofWrappers = []any{}
	file_internal_api_grpc_proto_protofile_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_grpc_proto_protofile_proto_rawDesc), len(file_internal_api_grpc_proto_protofile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_internal_api_grpc_proto_protofile_proto_goTypes,
		DependencyIndexes: file_internal_api_grpc_proto_protofile_proto_depIdxs,
		MessageInfos:      file_internal_api_grpc_proto_protofile_proto_msgTypes,
	}.Build()
	File_internal_api_grpc_proto_protofile_proto = out.File
	file_internal_api_grpc_proto_protofile_proto_goTypes = nil
	file_internal_api_grpc_proto_protofile_proto_depIdxs = nil
}
