// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: internal/api/grpc/proto/protofile.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RestaurantService_GetRestaurantDetails_FullMethodName     = "/proto.RestaurantService/GetRestaurantDetails"
	RestaurantService_CreateRestaurant_FullMethodName         = "/proto.RestaurantService/CreateRestaurant"
	RestaurantService_UpdateRestaurant_FullMethodName         = "/proto.RestaurantService/UpdateRestaurant"
	RestaurantService_CompareRestaurantDetails_FullMethodName = "/proto.RestaurantService/CompareRestaurantDetails"
)

// RestaurantServiceClient is the client API for RestaurantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestaurantServiceClient interface {
	GetRestaurantDetails(ctx context.Context, in *GetRestaurantDetailsRequest, opts ...grpc.CallOption) (*GetRestaurantDetailsResponse, error)
	CreateRestaurant(ctx context.Context, in *CreateRestaurantRequest, opts ...grpc.CallOption) (*CreateRestaurantResponse, error)
	UpdateRestaurant(ctx context.Context, in *UpdateRestaurantRequest, opts ...grpc.CallOption) (*UpdateRestaurantResponse, error)
	CompareRestaurantDetails(ctx context.Context, in *CompareRestaurantDetailsRequest, opts ...grpc.CallOption) (*CompareRestaurantDetailsResponse, error)
}

type restaurantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRestaurantServiceClient(cc grpc.ClientConnInterface) RestaurantServiceClient {
	return &restaurantServiceClient{cc}
}

func (c *restaurantServiceClient) GetRestaurantDetails(ctx context.Context, in *GetRestaurantDetailsRequest, opts ...grpc.CallOption) (*GetRestaurantDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRestaurantDetailsResponse)
	err := c.cc.Invoke(ctx, RestaurantService_GetRestaurantDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) CreateRestaurant(ctx context.Context, in *CreateRestaurantRequest, opts ...grpc.CallOption) (*CreateRestaurantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRestaurantResponse)
	err := c.cc.Invoke(ctx, RestaurantService_CreateRestaurant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) UpdateRestaurant(ctx context.Context, in *UpdateRestaurantRequest, opts ...grpc.CallOption) (*UpdateRestaurantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRestaurantResponse)
	err := c.cc.Invoke(ctx, RestaurantService_UpdateRestaurant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) CompareRestaurantDetails(ctx context.Context, in *CompareRestaurantDetailsRequest, opts ...grpc.CallOption) (*CompareRestaurantDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareRestaurantDetailsResponse)
	err := c.cc.Invoke(ctx, RestaurantService_CompareRestaurantDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestaurantServiceServer is the server API for RestaurantService service.
// All implementations must embed UnimplementedRestaurantServiceServer
// for forward compatibility.
type RestaurantServiceServer interface {
	GetRestaurantDetails(context.Context, *GetRestaurantDetailsRequest) (*GetRestaurantDetailsResponse, error)
	CreateRestaurant(context.Context, *CreateRestaurantRequest) (*CreateRestaurantResponse, error)
	UpdateRestaurant(context.Context, *UpdateRestaurantRequest) (*UpdateRestaurantResponse, error)
	CompareRestaurantDetails(context.Context, *CompareRestaurantDetailsRequest) (*CompareRestaurantDetailsResponse, error)
	mustEmbedUnimplementedRestaurantServiceServer()
}

// UnimplementedRestaurantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRestaurantServiceServer struct{}

func (UnimplementedRestaurantServiceServer) GetRestaurantDetails(context.Context, *GetRestaurantDetailsRequest) (*GetRestaurantDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRestaurantDetails not implemented")
}
func (UnimplementedRestaurantServiceServer) CreateRestaurant(context.Context, *CreateRestaurantRequest) (*CreateRestaurantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRestaurant not implemented")
}
func (UnimplementedRestaurantServiceServer) UpdateRestaurant(context.Context, *UpdateRestaurantRequest) (*UpdateRestaurantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRestaurant not implemented")
}
func (UnimplementedRestaurantServiceServer) CompareRestaurantDetails(context.Context, *CompareRestaurantDetailsRequest) (*CompareRestaurantDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompareRestaurantDetails not implemented")
}
func (UnimplementedRestaurantServiceServer) mustEmbedUnimplementedRestaurantServiceServer() {}
func (UnimplementedRestaurantServiceServer) testEmbeddedByValue()                           {}

// UnsafeRestaurantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestaurantServiceServer will
// result in compilation errors.
type UnsafeRestaurantServiceServer interface {
	mustEmbedUnimplementedRestaurantServiceServer()
}

func RegisterRestaurantServiceServer(s grpc.ServiceRegistrar, srv RestaurantServiceServer) {
	// If the following call panics, it indicates UnimplementedRestaurantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RestaurantService_ServiceDesc, srv)
}

func _RestaurantService_GetRestaurantDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestaurantDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).GetRestaurantDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_GetRestaurantDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).GetRestaurantDetails(ctx, req.(*GetRestaurantDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_CreateRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).CreateRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_CreateRestaurant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).CreateRestaurant(ctx, req.(*CreateRestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_UpdateRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).UpdateRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_UpdateRestaurant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).UpdateRestaurant(ctx, req.(*UpdateRestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_CompareRestaurantDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareRestaurantDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).CompareRestaurantDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantService_CompareRestaurantDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).CompareRestaurantDetails(ctx, req.(*CompareRestaurantDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RestaurantService_ServiceDesc is the grpc.ServiceDesc for RestaurantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestaurantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RestaurantService",
	HandlerType: (*RestaurantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRestaurantDetails",
			Handler:    _RestaurantService_GetRestaurantDetails_Handler,
		},
		{
			MethodName: "CreateRestaurant",
			Handler:    _RestaurantService_CreateRestaurant_Handler,
		},
		{
			MethodName: "UpdateRestaurant",
			Handler:    _RestaurantService_UpdateRestaurant_Handler,
		},
		{
			MethodName: "CompareRestaurantDetails",
			Handler:    _RestaurantService_CompareRestaurantDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/grpc/proto/protofile.proto",
}

const (
	RestaurantToBookingService_GetWorkingHours_FullMethodName = "/proto.RestaurantToBookingService/GetWorkingHours"
)

// RestaurantToBookingServiceClient is the client API for RestaurantToBookingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestaurantToBookingServiceClient interface {
	GetWorkingHours(ctx context.Context, in *WorkingHoursRequest, opts ...grpc.CallOption) (*WorkingHoursResponse, error)
}

type restaurantToBookingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRestaurantToBookingServiceClient(cc grpc.ClientConnInterface) RestaurantToBookingServiceClient {
	return &restaurantToBookingServiceClient{cc}
}

func (c *restaurantToBookingServiceClient) GetWorkingHours(ctx context.Context, in *WorkingHoursRequest, opts ...grpc.CallOption) (*WorkingHoursResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkingHoursResponse)
	err := c.cc.Invoke(ctx, RestaurantToBookingService_GetWorkingHours_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestaurantToBookingServiceServer is the server API for RestaurantToBookingService service.
// All implementations must embed UnimplementedRestaurantToBookingServiceServer
// for forward compatibility.
type RestaurantToBookingServiceServer interface {
	GetWorkingHours(context.Context, *WorkingHoursRequest) (*WorkingHoursResponse, error)
	mustEmbedUnimplementedRestaurantToBookingServiceServer()
}

// UnimplementedRestaurantToBookingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRestaurantToBookingServiceServer struct{}

func (UnimplementedRestaurantToBookingServiceServer) GetWorkingHours(context.Context, *WorkingHoursRequest) (*WorkingHoursResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkingHours not implemented")
}
func (UnimplementedRestaurantToBookingServiceServer) mustEmbedUnimplementedRestaurantToBookingServiceServer() {
}
func (UnimplementedRestaurantToBookingServiceServer) testEmbeddedByValue() {}

// UnsafeRestaurantToBookingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestaurantToBookingServiceServer will
// result in compilation errors.
type UnsafeRestaurantToBookingServiceServer interface {
	mustEmbedUnimplementedRestaurantToBookingServiceServer()
}

func RegisterRestaurantToBookingServiceServer(s grpc.ServiceRegistrar, srv RestaurantToBookingServiceServer) {
	// If the following call panics, it indicates UnimplementedRestaurantToBookingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RestaurantToBookingService_ServiceDesc, srv)
}

func _RestaurantToBookingService_GetWorkingHours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkingHoursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantToBookingServiceServer).GetWorkingHours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantToBookingService_GetWorkingHours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantToBookingServiceServer).GetWorkingHours(ctx, req.(*WorkingHoursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RestaurantToBookingService_ServiceDesc is the grpc.ServiceDesc for RestaurantToBookingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestaurantToBookingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RestaurantToBookingService",
	HandlerType: (*RestaurantToBookingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWorkingHours",
			Handler:    _RestaurantToBookingService_GetWorkingHours_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/grpc/proto/protofile.proto",
}

const (
	RestaurantToReviewService_GetRestaurantStats_FullMethodName = "/proto.RestaurantToReviewService/GetRestaurantStats"
)

// RestaurantToReviewServiceClient is the client API for RestaurantToReviewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestaurantToReviewServiceClient interface {
	GetRestaurantStats(ctx context.Context, in *GetRestaurantStatsRequest, opts ...grpc.CallOption) (*GetRestaurantStatsResponse, error)
}

type restaurantToReviewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRestaurantToReviewServiceClient(cc grpc.ClientConnInterface) RestaurantToReviewServiceClient {
	return &restaurantToReviewServiceClient{cc}
}

func (c *restaurantToReviewServiceClient) GetRestaurantStats(ctx context.Context, in *GetRestaurantStatsRequest, opts ...grpc.CallOption) (*GetRestaurantStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRestaurantStatsResponse)
	err := c.cc.Invoke(ctx, RestaurantToReviewService_GetRestaurantStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestaurantToReviewServiceServer is the server API for RestaurantToReviewService service.
// All implementations must embed UnimplementedRestaurantToReviewServiceServer
// for forward compatibility.
type RestaurantToReviewServiceServer interface {
	GetRestaurantStats(context.Context, *GetRestaurantStatsRequest) (*GetRestaurantStatsResponse, error)
	mustEmbedUnimplementedRestaurantToReviewServiceServer()
}

// UnimplementedRestaurantToReviewServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRestaurantToReviewServiceServer struct{}

func (UnimplementedRestaurantToReviewServiceServer) GetRestaurantStats(context.Context, *GetRestaurantStatsRequest) (*GetRestaurantStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRestaurantStats not implemented")
}
func (UnimplementedRestaurantToReviewServiceServer) mustEmbedUnimplementedRestaurantToReviewServiceServer() {
}
func (UnimplementedRestaurantToReviewServiceServer) testEmbeddedByValue() {}

// UnsafeRestaurantToReviewServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestaurantToReviewServiceServer will
// result in compilation errors.
type UnsafeRestaurantToReviewServiceServer interface {
	mustEmbedUnimplementedRestaurantToReviewServiceServer()
}

func RegisterRestaurantToReviewServiceServer(s grpc.ServiceRegistrar, srv RestaurantToReviewServiceServer) {
	// If the following call panics, it indicates UnimplementedRestaurantToReviewServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RestaurantToReviewService_ServiceDesc, srv)
}

func _RestaurantToReviewService_GetRestaurantStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestaurantStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantToReviewServiceServer).GetRestaurantStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestaurantToReviewService_GetRestaurantStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantToReviewServiceServer).GetRestaurantStats(ctx, req.(*GetRestaurantStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RestaurantToReviewService_ServiceDesc is the grpc.ServiceDesc for RestaurantToReviewService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestaurantToReviewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RestaurantToReviewService",
	HandlerType: (*RestaurantToReviewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRestaurantStats",
			Handler:    _RestaurantToReviewService_GetRestaurantStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/grpc/proto/protofile.proto",
}
