apiVersion: v1
kind: Secret
metadata:
  name: cdc-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
{{- range $key, $value := .Values.env.secrets }}
  {{ $key }}: "{{ $value }}"
{{- end }}
