apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: {{ .Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: otel-collector-sa@{{ .Values.gcpProject }}.iam.gserviceaccount.com
