// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: internal/api/grpc/proto/protofile.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSlotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int32                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	TimeStart     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSlotsRequest) Reset() {
	*x = GetSlotsRequest{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSlotsRequest) ProtoMessage() {}

func (x *GetSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSlotsRequest.ProtoReflect.Descriptor instead.
func (*GetSlotsRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{0}
}

func (x *GetSlotsRequest) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *GetSlotsRequest) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

type GetSlotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int32                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	MaxSlots      int32                  `protobuf:"varint,2,opt,name=max_slots,json=maxSlots,proto3" json:"max_slots,omitempty"`
	CurrentSlots  int32                  `protobuf:"varint,3,opt,name=current_slots,json=currentSlots,proto3" json:"current_slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSlotsResponse) Reset() {
	*x = GetSlotsResponse{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSlotsResponse) ProtoMessage() {}

func (x *GetSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSlotsResponse.ProtoReflect.Descriptor instead.
func (*GetSlotsResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{1}
}

func (x *GetSlotsResponse) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *GetSlotsResponse) GetMaxSlots() int32 {
	if x != nil {
		return x.MaxSlots
	}
	return 0
}

func (x *GetSlotsResponse) GetCurrentSlots() int32 {
	if x != nil {
		return x.CurrentSlots
	}
	return 0
}

type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RestaurantId  int32                  `protobuf:"varint,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	BookingRange  *TimeRange             `protobuf:"bytes,4,opt,name=booking_range,json=bookingRange,proto3" json:"booking_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBookingRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateBookingRequest) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *CreateBookingRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateBookingRequest) GetBookingRange() *TimeRange {
	if x != nil {
		return x.BookingRange
	}
	return nil
}

type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RestaurantId  int32                  `protobuf:"varint,3,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	BookingRange  *TimeRange             `protobuf:"bytes,5,opt,name=booking_range,json=bookingRange,proto3" json:"booking_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{3}
}

func (x *Booking) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Booking) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Booking) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *Booking) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Booking) GetBookingRange() *TimeRange {
	if x != nil {
		return x.BookingRange
	}
	return nil
}

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeStart     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	TimeEnd       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{4}
}

func (x *TimeRange) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

func (x *TimeRange) GetTimeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeEnd
	}
	return nil
}

var File_internal_api_grpc_proto_protofile_proto protoreflect.FileDescriptor

const file_internal_api_grpc_proto_protofile_proto_rawDesc = "" +
	"\n" +
	"'internal/api/grpc/proto/protofile.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"q\n" +
	"\x0fGetSlotsRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x05R\frestaurantId\x129\n" +
	"\n" +
	"time_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\"y\n" +
	"\x10GetSlotsResponse\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x05R\frestaurantId\x12\x1b\n" +
	"\tmax_slots\x18\x02 \x01(\x05R\bmaxSlots\x12#\n" +
	"\rcurrent_slots\x18\x03 \x01(\x05R\fcurrentSlots\"\xa7\x01\n" +
	"\x14CreateBookingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\x05R\frestaurantId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x125\n" +
	"\rbooking_range\x18\x04 \x01(\v2\x10.proto.TimeRangeR\fbookingRange\"\xaa\x01\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12#\n" +
	"\rrestaurant_id\x18\x03 \x01(\x05R\frestaurantId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x125\n" +
	"\rbooking_range\x18\x05 \x01(\v2\x10.proto.TimeRangeR\fbookingRange\"}\n" +
	"\tTimeRange\x129\n" +
	"\n" +
	"time_start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\x125\n" +
	"\btime_end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\atimeEnd2P\n" +
	"\x11RestaurantService\x12;\n" +
	"\bGetSlots\x12\x16.proto.GetSlotsRequest\x1a\x17.proto.GetSlotsResponse2N\n" +
	"\x0eBookingService\x12<\n" +
	"\rCreateBooking\x12\x1b.proto.CreateBookingRequest\x1a\x0e.proto.BookingB\bZ\x06/pb;pbb\x06proto3"

var (
	file_internal_api_grpc_proto_protofile_proto_rawDescOnce sync.Once
	file_internal_api_grpc_proto_protofile_proto_rawDescData []byte
)

func file_internal_api_grpc_proto_protofile_proto_rawDescGZIP() []byte {
	file_internal_api_grpc_proto_protofile_proto_rawDescOnce.Do(func() {
		file_internal_api_grpc_proto_protofile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_grpc_proto_protofile_proto_rawDesc), len(file_internal_api_grpc_proto_protofile_proto_rawDesc)))
	})
	return file_internal_api_grpc_proto_protofile_proto_rawDescData
}

var file_internal_api_grpc_proto_protofile_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_api_grpc_proto_protofile_proto_goTypes = []any{
	(*GetSlotsRequest)(nil),       // 0: proto.GetSlotsRequest
	(*GetSlotsResponse)(nil),      // 1: proto.GetSlotsResponse
	(*CreateBookingRequest)(nil),  // 2: proto.CreateBookingRequest
	(*Booking)(nil),               // 3: proto.Booking
	(*TimeRange)(nil),             // 4: proto.TimeRange
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_internal_api_grpc_proto_protofile_proto_depIdxs = []int32{
	5, // 0: proto.GetSlotsRequest.time_start:type_name -> google.protobuf.Timestamp
	4, // 1: proto.CreateBookingRequest.booking_range:type_name -> proto.TimeRange
	4, // 2: proto.Booking.booking_range:type_name -> proto.TimeRange
	5, // 3: proto.TimeRange.time_start:type_name -> google.protobuf.Timestamp
	5, // 4: proto.TimeRange.time_end:type_name -> google.protobuf.Timestamp
	0, // 5: proto.RestaurantService.GetSlots:input_type -> proto.GetSlotsRequest
	2, // 6: proto.BookingService.CreateBooking:input_type -> proto.CreateBookingRequest
	1, // 7: proto.RestaurantService.GetSlots:output_type -> proto.GetSlotsResponse
	3, // 8: proto.BookingService.CreateBooking:output_type -> proto.Booking
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_api_grpc_proto_protofile_proto_init() }
func file_internal_api_grpc_proto_protofile_proto_init() {
	if File_internal_api_grpc_proto_protofile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_grpc_proto_protofile_proto_rawDesc), len(file_internal_api_grpc_proto_protofile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_api_grpc_proto_protofile_proto_goTypes,
		DependencyIndexes: file_internal_api_grpc_proto_protofile_proto_depIdxs,
		MessageInfos:      file_internal_api_grpc_proto_protofile_proto_msgTypes,
	}.Build()
	File_internal_api_grpc_proto_protofile_proto = out.File
	file_internal_api_grpc_proto_protofile_proto_goTypes = nil
	file_internal_api_grpc_proto_protofile_proto_depIdxs = nil
}
