x-common: &common
  restart: unless-stopped
  networks:
    - app-network

x-restaurant-db-config: &restaurant-db-config
  POSTGRES_HOST: restaurant_db
  POSTGRES_DB: ${RESTAURANT_POSTGRES_DB}
  POSTGRES_USER: ${RESTAURANT_POSTGRES_USER}
  POSTGRES_PASSWORD: ${RESTAURANT_POSTGRES_PASSWORD}

x-pg-healthcheck: &pg-healthcheck
  test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  interval: 5s
  timeout: 5s
  retries: 5

services:
  restaurant:
    build: ./restaurant/
    <<: *common
    environment:
      # Database
      <<: *restaurant-db-config
      APP_SERVER_PORT: ${RESTAURANT_SERVER_PORT}
      REVIEW_GRPC_ADDR: "review:${REVIEW_SERVER_PORT}"
      DB_MIN_CONNS: 4
      DB_MAX_CONNS: 20
      DB_MAX_CONN_LIFETIME: 15m
      DB_HEALTH_CHECK_PERIOD: 1m
      # App
      APP_LOG_LEVEL: debug
    depends_on:
      restaurant_db:
        condition: service_healthy
    volumes:
      - ./restaurant:/app

  restaurant_db:
    image: postgres:16
    <<: *common
    command: postgres -c ssl=off -c log_statement=ddl
    volumes:
      - restaurant_db_data:/var/lib/postgresql/data
      - ./restaurant/db_setup.sql:/docker-entrypoint-initdb.d/init.sql:Z
    environment:
      <<: *restaurant-db-config
    healthcheck:
      <<: *pg-healthcheck

volumes:
  restaurant_db_data: