x-common: &common
  restart: unless-stopped
  networks:
    - app-network

x-payment-db-config: &payment-db-config
  POSTGRES_HOST: payment_db
  POSTGRES_DB: ${PAYMENT_POSTGRES_DB}
  POSTGRES_USER: ${PAYMENT_POSTGRES_USER}
  POSTGRES_PASSWORD: ${PAYMENT_POSTGRES_PASSWORD}

x-pg-healthcheck: &pg-healthcheck
  test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  interval: 5s
  timeout: 5s
  retries: 5

services:
  payment:
    build: ./payment/
    <<: *common
    environment:
      # Database
      <<: *payment-db-config
      APP_SERVER_PORT: ${PAYMENT_SERVER_PORT}
      NOTIFICATION_GRPC_ADDR: "notification:${NOTIFICATION_SERVER_PORT}"
      DB_MIN_CONNS: 4
      DB_MAX_CONNS: 20
      DB_MAX_CONN_LIFETIME: 15m
      DB_HEALTH_CHECK_PERIOD: 1m
      # App
      APP_LOG_LEVEL: debug
    depends_on:
      payment_db:
        condition: service_healthy
    volumes:
      - ./payment:/app

  payment_db:
    image: postgres:16
    <<: *common
    command: postgres -c ssl=off -c log_statement=ddl
    volumes:
      - payment_db_data:/var/lib/postgresql/data
      - ./payment/db_setup.sql:/docker-entrypoint-initdb.d/init.sql:Z
    environment:
      <<: *payment-db-config
    healthcheck:
      <<: *pg-healthcheck

volumes:
  payment_db_data: