x-common: &common
  restart: unless-stopped
  networks:
    - app-network

x-pg-healthcheck: &pg-healthcheck
  test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  interval: 5s
  timeout: 5s
  retries: 5

services:
  booking:
    build: ./booking/
    <<: *common
    env_file:
      - ./config.env
      - ./booking/.env   # BOOKING_POSTGRES_PASSWORD, DB_PASS
    environment:
      DB_HOST: booking_db
      DB_NAME: mrfood_booking
      DB_USER: booking
      POSTGRES_DB: mrfood_booking
      POSTGRES_USER: booking
      APP_SERVER_PORT: 50053
    depends_on:
      booking_db:
        condition: service_healthy
    volumes:
      - ./booking:/app

  booking_db:
    image: postgres:16
    <<: *common
    command: postgres -c ssl=off -c log_statement=ddl
    volumes:
      - booking_db_data:/var/lib/postgresql/data
      - ./booking/db_setup.sql:/docker-entrypoint-initdb.d/init.sql:Z
    env_file:
      - ./booking/.env   # POSTGRES_PASSWORD
    environment:
      POSTGRES_DB: mrfood_booking
      POSTGRES_USER: booking
    healthcheck:
      <<: *pg-healthcheck

volumes:
  booking_db_data: