x-common: &common
  restart: unless-stopped
  networks:
    - app-network
    - kong-net

x-auth-db-config: &auth-db-config
  POSTGRES_HOST: auth_db
  POSTGRES_DB: mrfood_auth
  POSTGRES_USER: ${AUTH_POSTGRES_USER}
  POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}

x-pg-healthcheck: &pg-healthcheck
  test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  interval: 5s
  timeout: 5s
  retries: 5

services:
  auth:
    build: ./auth/
    ports: ["${AUTH_SERVER_PORT}:${AUTH_SERVER_PORT}"]
    <<: *common
    environment:
      # Database
      <<: *auth-db-config
      DB_MIN_CONNS: 4
      DB_MAX_CONNS: 20
      DB_MAX_CONN_LIFETIME: 15m
      DB_HEALTH_CHECK_PERIOD: 1m
      # Redis
      REDIS_HOST: auth_redis
      REDIS_PASS: ${AUTH_REDIS_PASS}
      REDIS_DB: 0
      # App
      APP_LOG_LEVEL: debug
      APP_JWT_ACCESS_TOKEN_SECRET: ${AUTH_JWT_ACCESS_TOKEN_SECRET}
      APP_JWT_REFRESH_TOKEN_SECRET: ${AUTH_JWT_REFRESH_TOKEN_SECRET}
    depends_on:
      auth_db:
        condition: service_healthy
      auth_redis:
        condition: service_healthy

  auth_db:
    image: postgres:16
    ports: ["${AUTH_POSTGRES_PORT}:5432"]
    <<: *common
    command: postgres -c ssl=off -c log_statement=ddl
    volumes:
      - auth_db_data:/var/lib/postgresql/data
      - ./auth/db_setup.sql:/docker-entrypoint-initdb.d/init.sql:Z
    environment:
      <<: *auth-db-config
    healthcheck:
      <<: *pg-healthcheck

  auth_redis:
    image: redis:7-alpine
    ports: ["${AUTH_REDIS_PORT}:6379"]
    <<: *common
    command: redis-server --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
  kong-net:
    driver: bridge
volumes:
  auth_db_data: