x-common: &common
  restart: unless-stopped
  networks:
    - app-network

x-restaurant-db-config: &restaurant-db-config
  POSTGRES_DB: ${RESTAURANT_POSTGRES_DB:-mrfood_restaurant}
  POSTGRES_USER: ${RESTAURANT_POSTGRES_USER:-restaurant}
  POSTGRES_PASSWORD: ${RESTAURANT_POSTGRES_PASSWORD:-restaurantsecret}

x-restaurant-app-db-config: &restaurant-app-db-config
  DB_HOST: restaurant_db
  DB_PORT: 5432
  DB_NAME: ${RESTAURANT_POSTGRES_DB:-mrfood_restaurant}
  DB_USER: ${RESTAURANT_POSTGRES_USER:-restaurant}
  DB_PASS: ${RESTAURANT_POSTGRES_PASSWORD:-restaurantsecret}

x-pg-healthcheck: &pg-healthcheck
  test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  interval: 5s
  timeout: 5s
  retries: 5

services:
  restaurant:
    build: ./restaurant/
    ports: ["${RESTAURANT_SERVER_PORT:-50052}:${RESTAURANT_SERVER_PORT:-50052}"]
    <<: *common
    environment:
      # Database
      <<: *restaurant-app-db-config
      APP_SERVER_PORT: ${RESTAURANT_SERVER_PORT:-50052}
      DB_MIN_CONNS: 4
      DB_MAX_CONNS: 20
      DB_MAX_CONN_LIFETIME: 15m
      DB_HEALTH_CHECK_PERIOD: 1m
      # App
      APP_LOG_LEVEL: debug
    depends_on:
      restaurant_db:
        condition: service_healthy
    volumes:
      - ./restaurant:/app

  restaurant_db:
    image: postgres:16
    ports: ["${RESTAURANT_DB_PORT:-5432}:5432"]
    <<: *common
    command: postgres -c ssl=off -c log_statement=ddl
    volumes:
      - restaurant_db_data:/var/lib/postgresql/data
      - ./restaurant/db_setup.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      <<: *restaurant-db-config
    healthcheck:
      <<: *pg-healthcheck

networks:
  app-network:
    driver: bridge

volumes:
  restaurant_db_data: