x-common: &common
  restart: unless-stopped
  networks:
    - app-network

x-pg-healthcheck: &pg-healthcheck
  test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  interval: 5s
  timeout: 5s
  retries: 5

services:
  sponsor:
    build: ./sponsor/
    <<: *common
    env_file:
      - ./config.env
      - ./sponsor/.env   # SPONSOR_POSTGRES_PASSWORD
    depends_on:
      sponsor_db:
        condition: service_healthy
    volumes:
      - ./sponsor:/app

  sponsor_db:
    image: postgres:16
    <<: *common
    command: postgres -c ssl=off -c log_statement=ddl
    volumes:
      - sponsor_db_data:/var/lib/postgresql/data
      - ./sponsor/db_setup.sql:/docker-entrypoint-initdb.d/init.sql:Z
    env_file:
      - ./sponsor/.env   # POSTGRES_PASSWORD
    environment:
      POSTGRES_DB: ${SPONSOR_POSTGRES_DB}
      POSTGRES_USER: ${SPONSOR_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SPONSOR_POSTGRES_PASSWORD}
    healthcheck:
      <<: *pg-healthcheck

volumes:
  sponsor_db_data: