x-common: &common
  restart: unless-stopped
  networks:
    - app-network

x-pg-healthcheck: &pg-healthcheck
  test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  interval: 5s
  timeout: 5s
  retries: 5

services:
  restaurant:
    build: ./restaurant/
    <<: *common
    env_file:
      - ./config.env
      - ./restaurant/.env   # RESTAURANT_POSTGRES_PASSWORD
    environment:
      POSTGRES_HOST: restaurant_db
      POSTGRES_DB: mrfood_restaurant
      POSTGRES_USER: restaurant
      APP_SERVER_PORT: 50052
    depends_on:
      restaurant_db:
        condition: service_healthy
    volumes:
      - ./restaurant:/app

  restaurant_db:
    image: postgres:16
    <<: *common
    command: postgres -c ssl=off -c log_statement=ddl -c wal_level=logical -c max_wal_senders=10 -c max_replication_slots=10
    volumes:
      - restaurant_db_data:/var/lib/postgresql/data
      - ./restaurant/db_setup.sql:/docker-entrypoint-initdb.d/init.sql:Z
    env_file:
      - ./restaurant/.env   # POSTGRES_PASSWORD
    environment:
      POSTGRES_DB: mrfood_restaurant
      POSTGRES_USER: restaurant
    healthcheck:
      <<: *pg-healthcheck

volumes:
  restaurant_db_data: