// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/protofile.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_protofile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protofile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_protofile_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_proto_protofile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protofile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_protofile_proto_rawDescGZIP(), []int{1}
}

func (x *Pong) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_protofile_proto protoreflect.FileDescriptor

const file_proto_protofile_proto_rawDesc = "" +
	"\n" +
	"\x15proto/protofile.proto\x12\x05proto\"\x16\n" +
	"\x04Ping\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x16\n" +
	"\x04Pong\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id2\xb8\x01\n" +
	"\x0fTemplateService\x12$\n" +
	"\bPingPong\x12\v.proto.Ping\x1a\v.proto.Pong\x12'\n" +
	"\tManyPings\x12\v.proto.Ping\x1a\v.proto.Pong(\x01\x12'\n" +
	"\tManyPongs\x12\v.proto.Ping\x1a\v.proto.Pong0\x01\x12-\n" +
	"\rManyPingPongs\x12\v.proto.Ping\x1a\v.proto.Pong(\x010\x01B\bZ\x06/pb;pbb\x06proto3"

var (
	file_proto_protofile_proto_rawDescOnce sync.Once
	file_proto_protofile_proto_rawDescData []byte
)

func file_proto_protofile_proto_rawDescGZIP() []byte {
	file_proto_protofile_proto_rawDescOnce.Do(func() {
		file_proto_protofile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_protofile_proto_rawDesc), len(file_proto_protofile_proto_rawDesc)))
	})
	return file_proto_protofile_proto_rawDescData
}

var file_proto_protofile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_protofile_proto_goTypes = []any{
	(*Ping)(nil), // 0: proto.Ping
	(*Pong)(nil), // 1: proto.Pong
}
var file_proto_protofile_proto_depIdxs = []int32{
	0, // 0: proto.TemplateService.PingPong:input_type -> proto.Ping
	0, // 1: proto.TemplateService.ManyPings:input_type -> proto.Ping
	0, // 2: proto.TemplateService.ManyPongs:input_type -> proto.Ping
	0, // 3: proto.TemplateService.ManyPingPongs:input_type -> proto.Ping
	1, // 4: proto.TemplateService.PingPong:output_type -> proto.Pong
	1, // 5: proto.TemplateService.ManyPings:output_type -> proto.Pong
	1, // 6: proto.TemplateService.ManyPongs:output_type -> proto.Pong
	1, // 7: proto.TemplateService.ManyPingPongs:output_type -> proto.Pong
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_protofile_proto_init() }
func file_proto_protofile_proto_init() {
	if File_proto_protofile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_protofile_proto_rawDesc), len(file_proto_protofile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_protofile_proto_goTypes,
		DependencyIndexes: file_proto_protofile_proto_depIdxs,
		MessageInfos:      file_proto_protofile_proto_msgTypes,
	}.Build()
	File_proto_protofile_proto = out.File
	file_proto_protofile_proto_goTypes = nil
	file_proto_protofile_proto_depIdxs = nil
}
