// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/api/grpc/proto/protofile.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int32                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	RestaurantId  int32                  `protobuf:"varint,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Rating        int32                  `protobuf:"varint,5,opt,name=rating,proto3" json:"rating,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{0}
}

func (x *Review) GetReviewId() int32 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *Review) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *Review) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Review) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Review) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RestaurantStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int32                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	AverageRating float64                `protobuf:"fixed64,2,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	ReviewCount   int32                  `protobuf:"varint,3,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantStats) Reset() {
	*x = RestaurantStats{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantStats) ProtoMessage() {}

func (x *RestaurantStats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantStats.ProtoReflect.Descriptor instead.
func (*RestaurantStats) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{1}
}

func (x *RestaurantStats) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *RestaurantStats) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *RestaurantStats) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Pages         int32                  `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{2}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Pagination) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

type GetReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int32                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Page          *int32                 `protobuf:"varint,2,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Limit         *int32                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsRequest) Reset() {
	*x = GetReviewsRequest{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsRequest) ProtoMessage() {}

func (x *GetReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsRequest.ProtoReflect.Descriptor instead.
func (*GetReviewsRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{3}
}

func (x *GetReviewsRequest) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *GetReviewsRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *GetReviewsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int32                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReviewRequest) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *CreateReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CreateReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type UpdateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int32                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	Comment       *string                `protobuf:"bytes,2,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	Rating        *int32                 `protobuf:"varint,3,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReviewRequest) Reset() {
	*x = UpdateReviewRequest{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReviewRequest) ProtoMessage() {}

func (x *UpdateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReviewRequest.ProtoReflect.Descriptor instead.
func (*UpdateReviewRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateReviewRequest) GetReviewId() int32 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *UpdateReviewRequest) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *UpdateReviewRequest) GetRating() int32 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

type DeleteReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int32                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewRequest) Reset() {
	*x = DeleteReviewRequest{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewRequest) ProtoMessage() {}

func (x *DeleteReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewRequest.ProtoReflect.Descriptor instead.
func (*DeleteReviewRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteReviewRequest) GetReviewId() int32 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

type GetRestaurantStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int32                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantStatsRequest) Reset() {
	*x = GetRestaurantStatsRequest{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantStatsRequest) ProtoMessage() {}

func (x *GetRestaurantStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantStatsRequest.ProtoReflect.Descriptor instead.
func (*GetRestaurantStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{7}
}

func (x *GetRestaurantStatsRequest) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

type GetReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsResponse) Reset() {
	*x = GetReviewsResponse{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsResponse) ProtoMessage() {}

func (x *GetReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsResponse.ProtoReflect.Descriptor instead.
func (*GetReviewsResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{8}
}

func (x *GetReviewsResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

func (x *GetReviewsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CreateReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewResponse) Reset() {
	*x = CreateReviewResponse{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewResponse) ProtoMessage() {}

func (x *CreateReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewResponse.ProtoReflect.Descriptor instead.
func (*CreateReviewResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{9}
}

func (x *CreateReviewResponse) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type UpdateReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReviewResponse) Reset() {
	*x = UpdateReviewResponse{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReviewResponse) ProtoMessage() {}

func (x *UpdateReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReviewResponse.ProtoReflect.Descriptor instead.
func (*UpdateReviewResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateReviewResponse) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type DeleteReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewResponse) Reset() {
	*x = DeleteReviewResponse{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewResponse) ProtoMessage() {}

func (x *DeleteReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewResponse.ProtoReflect.Descriptor instead.
func (*DeleteReviewResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{11}
}

type GetRestaurantStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RestaurantStats *RestaurantStats       `protobuf:"bytes,1,opt,name=restaurant_stats,json=restaurantStats,proto3" json:"restaurant_stats,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRestaurantStatsResponse) Reset() {
	*x = GetRestaurantStatsResponse{}
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantStatsResponse) ProtoMessage() {}

func (x *GetRestaurantStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_protofile_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantStatsResponse.ProtoReflect.Descriptor instead.
func (*GetRestaurantStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_protofile_proto_rawDescGZIP(), []int{12}
}

func (x *GetRestaurantStatsResponse) GetRestaurantStats() *RestaurantStats {
	if x != nil {
		return x.RestaurantStats
	}
	return nil
}

var File_internal_api_grpc_proto_protofile_proto protoreflect.FileDescriptor

const file_internal_api_grpc_proto_protofile_proto_rawDesc = "" +
	"\n" +
	"'internal/api/grpc/proto/protofile.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd0\x01\n" +
	"\x06Review\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\x05R\breviewId\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\x05R\frestaurantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x05R\x06rating\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x80\x01\n" +
	"\x0fRestaurantStats\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x05R\frestaurantId\x12%\n" +
	"\x0eaverage_rating\x18\x02 \x01(\x01R\raverageRating\x12!\n" +
	"\freview_count\x18\x03 \x01(\x05R\vreviewCount\"b\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x14\n" +
	"\x05pages\x18\x04 \x01(\x05R\x05pages\"\x7f\n" +
	"\x11GetReviewsRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x05R\frestaurantId\x12\x17\n" +
	"\x04page\x18\x02 \x01(\x05H\x00R\x04page\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x05H\x01R\x05limit\x88\x01\x01B\a\n" +
	"\x05_pageB\b\n" +
	"\x06_limit\"l\n" +
	"\x13CreateReviewRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x05R\frestaurantId\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\"\x85\x01\n" +
	"\x13UpdateReviewRequest\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\x05R\breviewId\x12\x1d\n" +
	"\acomment\x18\x02 \x01(\tH\x00R\acomment\x88\x01\x01\x12\x1b\n" +
	"\x06rating\x18\x03 \x01(\x05H\x01R\x06rating\x88\x01\x01B\n" +
	"\n" +
	"\b_commentB\t\n" +
	"\a_rating\"2\n" +
	"\x13DeleteReviewRequest\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\x05R\breviewId\"@\n" +
	"\x19GetRestaurantStatsRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x05R\frestaurantId\"p\n" +
	"\x12GetReviewsResponse\x12'\n" +
	"\areviews\x18\x01 \x03(\v2\r.proto.ReviewR\areviews\x121\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x11.proto.PaginationR\n" +
	"pagination\"=\n" +
	"\x14CreateReviewResponse\x12%\n" +
	"\x06review\x18\x01 \x01(\v2\r.proto.ReviewR\x06review\"=\n" +
	"\x14UpdateReviewResponse\x12%\n" +
	"\x06review\x18\x01 \x01(\v2\r.proto.ReviewR\x06review\"\x16\n" +
	"\x14DeleteReviewResponse\"_\n" +
	"\x1aGetRestaurantStatsResponse\x12A\n" +
	"\x10restaurant_stats\x18\x01 \x01(\v2\x16.proto.RestaurantStatsR\x0frestaurantStats2\xad\x02\n" +
	"\rReviewService\x12A\n" +
	"\n" +
	"GetReviews\x12\x18.proto.GetReviewsRequest\x1a\x19.proto.GetReviewsResponse\x12G\n" +
	"\fCreateReview\x12\x1a.proto.CreateReviewRequest\x1a\x1b.proto.CreateReviewResponse\x12G\n" +
	"\fUpdateReview\x12\x1a.proto.UpdateReviewRequest\x1a\x1b.proto.UpdateReviewResponse\x12G\n" +
	"\fDeleteReview\x12\x1a.proto.DeleteReviewRequest\x1a\x1b.proto.DeleteReviewResponse2s\n" +
	"\x16ReviewToDetailsService\x12Y\n" +
	"\x12GetRestaurantStats\x12 .proto.GetRestaurantStatsRequest\x1a!.proto.GetRestaurantStatsResponseB\bZ\x06/pb;pbb\x06proto3"

var (
	file_internal_api_grpc_proto_protofile_proto_rawDescOnce sync.Once
	file_internal_api_grpc_proto_protofile_proto_rawDescData []byte
)

func file_internal_api_grpc_proto_protofile_proto_rawDescGZIP() []byte {
	file_internal_api_grpc_proto_protofile_proto_rawDescOnce.Do(func() {
		file_internal_api_grpc_proto_protofile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_grpc_proto_protofile_proto_rawDesc), len(file_internal_api_grpc_proto_protofile_proto_rawDesc)))
	})
	return file_internal_api_grpc_proto_protofile_proto_rawDescData
}

var file_internal_api_grpc_proto_protofile_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_api_grpc_proto_protofile_proto_goTypes = []any{
	(*Review)(nil),                     // 0: proto.Review
	(*RestaurantStats)(nil),            // 1: proto.RestaurantStats
	(*Pagination)(nil),                 // 2: proto.Pagination
	(*GetReviewsRequest)(nil),          // 3: proto.GetReviewsRequest
	(*CreateReviewRequest)(nil),        // 4: proto.CreateReviewRequest
	(*UpdateReviewRequest)(nil),        // 5: proto.UpdateReviewRequest
	(*DeleteReviewRequest)(nil),        // 6: proto.DeleteReviewRequest
	(*GetRestaurantStatsRequest)(nil),  // 7: proto.GetRestaurantStatsRequest
	(*GetReviewsResponse)(nil),         // 8: proto.GetReviewsResponse
	(*CreateReviewResponse)(nil),       // 9: proto.CreateReviewResponse
	(*UpdateReviewResponse)(nil),       // 10: proto.UpdateReviewResponse
	(*DeleteReviewResponse)(nil),       // 11: proto.DeleteReviewResponse
	(*GetRestaurantStatsResponse)(nil), // 12: proto.GetRestaurantStatsResponse
	(*timestamppb.Timestamp)(nil),      // 13: google.protobuf.Timestamp
}
var file_internal_api_grpc_proto_protofile_proto_depIdxs = []int32{
	13, // 0: proto.Review.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: proto.GetReviewsResponse.reviews:type_name -> proto.Review
	2,  // 2: proto.GetReviewsResponse.pagination:type_name -> proto.Pagination
	0,  // 3: proto.CreateReviewResponse.review:type_name -> proto.Review
	0,  // 4: proto.UpdateReviewResponse.review:type_name -> proto.Review
	1,  // 5: proto.GetRestaurantStatsResponse.restaurant_stats:type_name -> proto.RestaurantStats
	3,  // 6: proto.ReviewService.GetReviews:input_type -> proto.GetReviewsRequest
	4,  // 7: proto.ReviewService.CreateReview:input_type -> proto.CreateReviewRequest
	5,  // 8: proto.ReviewService.UpdateReview:input_type -> proto.UpdateReviewRequest
	6,  // 9: proto.ReviewService.DeleteReview:input_type -> proto.DeleteReviewRequest
	7,  // 10: proto.ReviewToDetailsService.GetRestaurantStats:input_type -> proto.GetRestaurantStatsRequest
	8,  // 11: proto.ReviewService.GetReviews:output_type -> proto.GetReviewsResponse
	9,  // 12: proto.ReviewService.CreateReview:output_type -> proto.CreateReviewResponse
	10, // 13: proto.ReviewService.UpdateReview:output_type -> proto.UpdateReviewResponse
	11, // 14: proto.ReviewService.DeleteReview:output_type -> proto.DeleteReviewResponse
	12, // 15: proto.ReviewToDetailsService.GetRestaurantStats:output_type -> proto.GetRestaurantStatsResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_api_grpc_proto_protofile_proto_init() }
func file_internal_api_grpc_proto_protofile_proto_init() {
	if File_internal_api_grpc_proto_protofile_proto != nil {
		return
	}
	file_internal_api_grpc_proto_protofile_proto_msgTypes[3].OneofWrappers = []any{}
	file_internal_api_grpc_proto_protofile_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_grpc_proto_protofile_proto_rawDesc), len(file_internal_api_grpc_proto_protofile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_api_grpc_proto_protofile_proto_goTypes,
		DependencyIndexes: file_internal_api_grpc_proto_protofile_proto_depIdxs,
		MessageInfos:      file_internal_api_grpc_proto_protofile_proto_msgTypes,
	}.Build()
	File_internal_api_grpc_proto_protofile_proto = out.File
	file_internal_api_grpc_proto_protofile_proto_goTypes = nil
	file_internal_api_grpc_proto_protofile_proto_depIdxs = nil
}
