apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storageSize }}
