name: Lint & Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: stable    
          cache: true
          cache-dependency-path: ./services/auth/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10
          working-directory: ./services/auth  

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26.1'
          cache: true
          cache-dependency-path: ./services/auth/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10
          working-directory: ./services/auth  
      - name: Build
        working-directory: ./services/auth
        run: go build -v ./...

      - name: Test
        working-directory: ./services/auth
        run: go test -v -race ./...

        
